ubiquitypress/hyku

app/controllers/hyku/registrations_controller.rb
app/views/devise/registrations/new.html.erb
config/locales/simple_form.en.yml

With reference to: "Contact form name field auto-populates with email address instead of name." on [UP-Hyku test plan](https://docs.google.com/spreadsheets/d/1l_ywidtmzV2jQ29D0IqOnuJf0kiVJr1SFDjTnVIJ-ec/edit?usp=sharing).
This adds a "Name" field when users sign up, which in turn allows the "Contact Form" to display a user name instead of an email address.

add user name field on sign up

---

app/forms/hyrax/generic_work_form.rb

Solves "Creative Commons licences would be better in the top default section of the submission." from [UP-Hyku test plan](https://docs.google.com/spreadsheets/d/1l_ywidtmzV2jQ29D0IqOnuJf0kiVJr1SFDjTnVIJ-ec/edit?usp=sharing)

add License to main fields for 'Add New Work' page

---

app/forms/hyrax/form_terms.rb
app/forms/hyrax/generic_work_form.rb
app/forms/hyrax/image_form.rb

License field now shows both on Generic Work and Image creation forms.

add 'license' to primary_terms applied to both Generic Work and Image

---

app/assets/stylesheets/hyku.scss

Override Bootstrap default color on hover from white to a grey - so if we style the navbar in white the Institution's name does not seem to disappear.
Trello card [#2576](https://trello.com/c/TbMnba2M)

Change to Logo color when hovering

---

Dockerfile
app/presenters/hyku/manifest_enabled_work_show_presenter.rb
app/views/hyrax/base/_when_no_file.html.erb
app/views/hyrax/base/show.html.erb
config/initializers/hyrax.rb
docker-entrypoint.sh
spec/factories/dataset.rb
spec/presenters/hyku/manifest_enabled_work_show_presenter_spec.rb

Our Trello card [#2632](https://trello.com/c/mqJYjxlq)
Changes proposed in this pull request:
* Files are no longer `required` to create a work (but can still be added);
* Users see a message indicating if a work does not have any associated file - for works they are allowed to see and not edit.
The message displays under "Items" see below:

Enable creation of metadata-only records

---

app/controllers/catalog_controller.rb
app/decorators/models/basic_metadata_decorator.rb
app/forms/hyrax/book_contribution_form.rb
app/forms/hyrax/book_form.rb
app/forms/hyrax/conference_item_form.rb
app/forms/hyrax/dataset_form.rb
app/forms/hyrax/form_terms.rb
app/forms/hyrax/journal_article_form.rb
app/forms/hyrax/report_form.rb
app/models/concerns/ubiquity/shared_metadata.rb
app/models/journal_article.rb
app/models/solr_document.rb
app/presenters/hyku/manifest_enabled_work_show_presenter.rb
app/services/institution_service.rb
app/services/refereed_service.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/records/edit_fields/_institution.html.erb
app/views/records/edit_fields/_refereed.html.erb
config/application.rb
config/authorities/institution.yml
config/authorities/refereed.yml
config/initializers/hyrax.rb
config/locales/journal_article.en.yml

Trello card [#2636](https://trello.com/c/M4N5FcIq)
Fields created or adapted:
- Institution
- Organistational Unit
- Peer-reviewed
- Identifier does not display anymore, instead there is: DOI, ISSN, and eISSN
- Funder
- Funder project reference
- Additional info
- Date created doesn not display anymore, instead there is: Date published, Date accepted, and Date submitted
- Journal title
- Issue
- Volume
- Pagination
- Article number
- Project name
- Rights holder
- Official link
More fields to be added
Work In Progress:
- Fields with drop-down lists don't save to database (Peer-reviewed and Institution)
- Some fields display on record views even when empty

Journal Article metadata template

---

app/controllers/catalog_controller.rb
app/forms/hyrax/book_contribution_form.rb
app/forms/hyrax/book_form.rb
app/forms/hyrax/conference_item_form.rb
app/forms/hyrax/dataset_form.rb
app/forms/hyrax/journal_article_form.rb
app/forms/hyrax/report_form.rb
app/models/concerns/ubiquity/basic_metadata_decorator.rb
app/models/concerns/ubiquity/shared_metadata.rb
app/models/solr_document.rb
app/presenters/hyku/manifest_enabled_work_show_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/records/edit_fields/_abstract.html.erb
config/locales/book.en.yml
config/locales/conference_item.en.yml
config/locales/journal_article.en.yml

More work following PR #20 to #27 
Trello cards [#2636](https://trello.com/c/M4N5FcIq), and [#2662](https://trello.com/c/ITjb2hGv) through [#2666](https://trello.com/c/R8L08tdz)
Global fields added:
- Abstract
- Place of publication
Both of these use different properties than "Abstract or Summary" and "Location" which they replace and get hidden in the forms: `self.terms -= %i[based_near description]`
Non-global fields added:
- Series name, Edition --> to Book, Book contribution, Conference item, and Report templates
- Event title, Event date, Book title --> to Conference Item template

Additional metadata fields

---

app/forms/hyrax/book_contribution_form.rb
app/forms/hyrax/book_form.rb
app/forms/hyrax/conference_item_form.rb
app/forms/hyrax/dataset_form.rb
app/forms/hyrax/generic_work_form.rb
app/forms/hyrax/image_form.rb
app/forms/hyrax/journal_article_form.rb
app/forms/hyrax/report_form.rb
app/models/concerns/ubiquity/basic_metadata_decorator.rb
app/renderers/resource_type_renderer.rb
app/services/resource_types_service.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/records/edit_fields/_resource_type.html.erb
config/authorities/resource_types.yml
config/locales/journal_article.en.yml

Trello card [#2691](https://trello.com/c/4WRrc90b)
Changes to Resource Type field:
- is a required field
- drop-down menu displays custom options according to the model
- default option is pre-selected
WIP - left to do:
- modify the display on search result to include only the sub-term without the model class name (i.e. "Book chapter" only instead of "BookContribution Book chapter") - this is done (by `app/renderers/resource_type_renderer.rb`) for the individual record show page

[WIP] Metadata: Resource Type custom options per template

---

app/controllers/catalog_controller.rb
app/forms/ubiquity/all_forms_shared_behaviour.rb
app/helpers/application_helper.rb
app/helpers/ubiquity/solr_search_display_helpers.rb
app/models/concerns/ubiquity/all_models_virtual_fields.rb
app/models/concerns/ubiquity/basic_metadata_decorator.rb
app/models/solr_document.rb
app/presenters/hyku/manifest_enabled_work_show_presenter.rb
app/services/related_identifier_type_service.rb
app/services/relation_type_service.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/records/edit_fields/_related_identifier.html.erb
app/views/shared/ubiquity/alternate_identifier/_alternate_identifier_js.html.erb
app/views/shared/ubiquity/related_identifier/_edit_array_hash_form.html.erb
app/views/shared/ubiquity/related_identifier/_edit_form.html.erb
app/views/shared/ubiquity/related_identifier/_new_form.html.erb
app/views/shared/ubiquity/related_identifier/_related_identifier_js.html.erb
app/views/shared/ubiquity/related_identifier/_show.html.erb
app/views/shared/ubiquity/related_identifier/_show_array_hash.html.erb
config/authorities/related_identifier_type.yml
config/authorities/relation_type.yml

Adds a multi-part field for Related identifier + Type of related identifier + Relationship of related identifier.
Follow up work on:
- Trello [#2636](https://trello.com/c/M4N5FcIq), and [#2662](https://trello.com/c/ITjb2hGv) through [#2666](https://trello.com/c/R8L08tdz)
- PR #20

Metadata: Related identifier multi-part field

---

config/locales/book.en.yml
config/locales/journal_article.en.yml

"ISBN" in capital letters on the template form. The default label was not being picked up from `config/locales/book.en.yml`, it is now in `config/locales/journal_article.en.yml`.

Fix label display

---

app/views/hyrax/base/_attribute_rows.html.erb
app/views/hyrax/base/_ubiquity_metadata.html.erb

Initial reordering of metadata fields so BL can test.
Card [#254](https://trello.com/c/Q70HJFYh)

Initial reordering of fields on work view

---

app/forms/hyrax/article_form.rb
app/forms/hyrax/book_contribution_form.rb
app/forms/hyrax/book_form.rb
app/forms/hyrax/conference_item_form.rb
app/forms/hyrax/dataset_form.rb
app/forms/hyrax/generic_work_form.rb
app/forms/hyrax/image_form.rb
app/forms/hyrax/report_form.rb
app/forms/ubiquity/all_forms_shared_behaviour.rb
app/forms/ubiquity/editor_metadata_form_behaviour.rb
app/views/records/edit_fields/_title.html.erb
app/views/shared/ubiquity/creator/_edit_array_hash_form.html.erb
app/views/shared/ubiquity/creator/_new_form.html.erb
config/locales/article.en.yml
config/locales/generic_work.en.yml

... according to BL specs.
Trello Card [#216](https://trello.com/c/06XrzT8Q)
Will address comment from Sara about multi-parts fields separately:
_"For me, having Orcid field and ISNI field separated by name fields doesn't make sense. Orcid & ISNI should sit next to each other. Not actually specced like this as we specced name identifier + id type as the fields and not specifically ISNI & Orcid.
Same with Contributor fields, ORcid & ISNI fields could do with being next to each other."_

Submission forms - reorder metadata fields

---

app/presenters/hyku/manifest_enabled_work_show_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/shared/_additional_citations.html.erb
spec/presenters/hyku/manifest_enabled_work_show_presenter_spec.rb

Change position of "Material/media" field on work show page;
Fix DOI not displaying in work show page.
Follow-up on #66 
Trello [#254](https://trello.com/c/Q70HJFYh)

Reordering of fields on work view

---

app/models/concerns/ubiquity/basic_metadata_decorator.rb

Abstract metadata field can only be filled in once.

Abstract 'multiple: false'

---

app/models/concerns/ubiquity/basic_metadata_decorator.rb

Revert last commit to be able to access records on live test site and remove data (more than 1 abstract) which breaks on`edit`.

revert change to abstract field

---

app/models/concerns/ubiquity/basic_metadata_decorator.rb

Follows #72  and  #73 
to make the `abstract` field accept only one text, this time after having removed the breaking data (more than 1 text) in records on the test site.

 Abstract 'multiple: false'

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/helpers/ubiquity/solr_search_display_helpers.rb

Trello #[264](https://trello.com/c/7EieLDwA)
Terms for the "Resource Type" metadata field are customised per model, thus we need to handle the display where the default produces the term id, i.e. "Article default Journal article" instead of "Journal article".
previous: 
now:
Linked to #30 , #57

Additional logic needed to display custom "Resource Type" metadata

---

app/controllers/concerns/ubiquity/breadcrumb_override.rb

Fixes double display of breadcrumb trail for logged in users. Following #93

Remove 'super'

---

app/renderers/hyrax/renderers/external_url_attribute_renderer.rb
app/views/hyrax/base/_attribute_rows.html.erb

Trello #[226](https://trello.com/c/qLL8hEl6)
- Rights Statement - draws from `hyrax/app/renderers/hyrax/renderers/rights_statement_attribute_renderer.rb`
Custom renderer for:
- Official link
- Related URL
- DOI

External URLs to open in a new tab, remove icon

---

app/views/hyrax/base/_attribute_rows.html.erb
config/locales/conference_item.en.yml
config/locales/dataset.en.yml
config/locales/report.en.yml

Trello #[242](https://trello.com/c/VnhetPtg)
Label "Official `URL`" (instead of 'link')
and "Related `URL`'"(instead or lower case 'url').

Display "Official URL" instead of "Official link"

---

app/assets/stylesheets/ubiquity.scss
app/views/_controls.html.erb

Trello #[248](https://trello.com/c/jnSXj9Tx)
On small screens, navbar to look like this:
Instead of this:

Homepage navbar to display only on 2 rows on small screens

---

app/renderers/hyrax/renderers/external_url_attribute_renderer.rb

Fixes issue observed on testing site; Trello #[226](https://trello.com/c/qLL8hEl6):
"If more than one 'Related URL' is entered, they display as one and makes one long incorrect URL"
Follow up on #97

Separate multiple URLs with a <br/>

---

app/views/shared/ubiquity/contributor/_edit_array_hash_form.html.erb
app/views/shared/ubiquity/contributor/_new_form.html.erb
app/views/shared/ubiquity/creator/_edit_array_hash_form.html.erb
app/views/shared/ubiquity/creator/_new_form.html.erb
app/views/shared/ubiquity/editor/_edit_array_hash_form.html.erb
app/views/shared/ubiquity/editor/_new_form.html.erb

Trello cards: #[195](https://trello.com/c/A4ZkGgna), #[202](https://trello.com/c/uief4f1M), #[224](https://trello.com/c/8swpoPQF)
Changes to Creator / Contributor / Editor form fields: 
- help text,
- UK spelling of 'organisation';
- reordering of sub-fields.

Changes to creator/contributor/editor metadata fields

---

app/views/shared/ubiquity/_editor_js.html.erb
app/views/shared/ubiquity/contributor/_contributor_js.html.erb
app/views/shared/ubiquity/contributor/_edit_array_hash_form.html.erb
app/views/shared/ubiquity/contributor/_new_form.html.erb
app/views/shared/ubiquity/editor/_edit_array_hash_form.html.erb
app/views/shared/ubiquity/editor/_new_form.html.erb

Addresses:
https://trello.com/c/YaWSaXia/245-01-on-submission-preselect-the-first-contributor-and-creator-name-type-fields-to-personal
https://trello.com/c/v2fdETCa/241-01-template-testing-contributor-type-field-disappears-if-contributor-name-type-organisational

preselecting contributor_name_type and editor_name_type now renders the right html form fields

---

app/assets/stylesheets/ubiquity.scss
app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/hyrax/homepage/_explore_collections.html.erb
app/views/hyrax/homepage/_featured.html.erb
app/views/hyrax/homepage/_featured_fields.html.erb
app/views/hyrax/homepage/_home_content.html.erb
app/views/hyrax/homepage/_recent_document.html.erb
app/views/hyrax/homepage/_recently_uploaded.html.erb
app/views/hyrax/homepage/_sortable_featured.html.erb
config/locales/hyrax.en.yml

As specified in Trello #[252](https://trello.com/c/wXDoUVmJ)
Homepage to look like:
Instead of:

Homepage content

---

app/models/concerns/ubiquity/all_models_virtual_fields.rb
app/models/concerns/ubiquity/editor_metadata_model_concern.rb

Resolve the issue of empty contributor still displaying as observed by Sara in this Trello card:
https://trello.com/c/0QcsuaJR/287-05-contributor-displays-in-front-end-even-when-empty-check-spec-re-test 
This can be reproduced in 2 ways:
1. Create a new work type but don't click the  'additional fields' button and then click save.
2. From an existing work, that is one that is already in the database but has no contributor, click edit, then save without clicking   'additional fields' button.
This is now fixed and pushed to Github.

stop empty contributor from saving

---

config/settings.yml

Disable public account signup - signup by invitation from an admin user remains.
Trello #[304](https://trello.com/c/O9VVq2x3)

Disable user sign-up

---

app/services/ubiquity/parse_json.rb
app/views/shared/ubiquity/collections/_show_document_list_row.html.erb

Ensure we don't iterate over nil.
Creator metadata is supposed to always return an array even when empty? but just incase of nil which is unlikely, I am calling the try method when calling to_sentence. Eg
(document.creator).try(:to_sentence)

dont't iterate over nil

---

app/views/hyrax/admin/workflows/index.html.erb

Fixes https://trello.com/c/ndkaPaYV/322-dashboard-review-submissions-depositor-column-shows-json-code-instead-of-name
Previous look:
Look after fix:

ensure review submission page renders json correctly

---

app/controllers/catalog_controller.rb

Remove all view options from search/browse
Resolves: https://trello.com/c/YmTaK3Qq/335-remove-all-view-options-from-search-browse

Remove all view options from search/browse

---

app/views/hyrax/base/_attribute_rows.html.erb

Fix empty 'Article number' field display in Works show page

---

app/models/concerns/ubiquity/all_models_virtual_fields.rb
app/models/concerns/ubiquity/editor_metadata_model_concern.rb
app/services/ubiquity/parse_json.rb
lib/tasks/creator_search.rake

- Filter from last name, like "Doe, Jane" Instead of "Jane Doe"
- Make sure the `creator_search` field is erased too when a creator is deleted.
- Changes to rake task so json "virtual fields" data is not lost.
Follow up on #109 
Trello #[276](https://trello.com/c/ENyC6Tmb)

Change display in creator facet

---

app/jobs/create_fcrepo_endpoint_job.rb
config/settings.yml

Trello #[285](https://trello.com/c/IXOS45lc)
When renaming a tenant from `<host>/proprietor/accounts/<id>/edit`, the Fedora endpoint `url` is currently nil, which brings the site down.
The changes in this PR save a correct `fcrepo_endpoint.url` on Account **Creation**.
:warning:  When **editing** an existing tenant account - which was saved prior to this code change, hence does not have a Fedora Endpoint URL - the 1st time, we need to type in the missing value: `http://fcrepo:8080/fcrepo/rest`
In rails console, see: `Account.find(<id>).fcrepo_endpoint.url`

Fix problem caused by renaming tenant account cname

---

Gemfile
Gemfile.lock
app/assets/stylesheets/ubiquity.scss
app/controllers/available_ubiquity_titles_controller.rb
app/services/ubiquity/datacite_client.rb
app/services/ubiquity/datacite_response.rb
app/views/hyrax/base/_guts4form.html.erb
app/views/hyrax/base/new.html.erb
app/views/records/edit_fields/_abstract.html.erb
app/views/records/edit_fields/_license.html.erb
app/views/shared/ubiquity/_datacite_doi.html.erb
app/views/shared/ubiquity/_datacite_js.html.erb
app/views/shared/ubiquity/_date_published.html.erb
app/views/shared/ubiquity/creator/_new_form.html.erb
config/locales/hyrax.en.yml
config/routes.rb

Initial implementation.
1. It can create creators based on authors with no given name using this api:
https://api.datacite.org/works/10.5438/0012
2. It can also create creators based on authors with given_name provided by the api as seen in this api:
https://api.datacite.org/works/10.5438/0012
3. If those fields has multiple creators or related_identifier they will be created as such.
4. It can handle different url format. It has been tested with:
https://api.datacite.org/works/10.5438/0012
api.datacite.org/works/10.5438/0012
/works/10.5438/0012
works/10.5438/0012
/10.5438/0012
10.5438/0012
5. I have added fields to auto-populate title, creator, date_published and related_identifier.
Yet to be added javascript wise is version, license, abstract

Datacite doi

---

.gitignore
lib/tasks/automatic_user.rake

Rake task to auto create user and assign admin role
You can't run it  locally though,  without following the instructions below
you will need to create a file in config, that is config/local_env.yml containing the following
DEFAULT_ADMIN_EMAIL: defautl_email1@ubiquitypress.com
DEFAULT_ADMIN_PASSWORD: ubiquity1
This file is ignored in .gitignore as it is just to test that environment variables are picked in the code.
Next in config/application.rb add:
config.before_configuration do
env_file = File.join(Rails.root, 'config', 'local_env.yml')
YAML.load(File.open(env_file)).each do |key, value|
ENV[key.to_s] = value
end if File.exists?(env_file)
end
The you can run it with :
bundle exec rake hyku:automatic_user:create

Rake task to auto create user and assign admin role

---

app/views/shared/ubiquity/file_sets/_actions.html.erb
app/views/shared/ubiquity/works/_actions.html.erb
app/views/shared/ubiquity/works/_member.html.erb

Addresses the request to  disable the Download button while files are embargoed:
https://trello.com/c/nSNzuyCG/164-05-testing-failed-user-as-a-user-i-want-to-see-the-embargo-release-date-or-lease-release-date-when-i-have-access-to-the-work-me

Disable the Download button while files are embargoed

---

app/views/shared/ubiquity/_datacite_js.html.erb

Fixes error message and datacite fields that were found notification

fix datacite for ie11 replace .val() with .html() for add input value

---

app/controllers/application_controller.rb

rescue from tenant not found and redirect to splash shared layer
Steps to test it:
Start the Hyku app, then try to navigate to a non-existent tenant, it should take you back to the splash page where you can click on any of the tenants listed there to redirect to where you want.

rescue from tenant not found and redirect to splash shared layer

---

app/assets/stylesheets/ubiquity.scss
app/views/hyrax/dashboard/collections/_list_works.html.erb
app/views/hyrax/homepage/_explore_collections.html.erb
app/views/hyrax/homepage/_featured_fields.html.erb
app/views/hyrax/my/works/_list_works.html.erb
app/views/shared/ubiquity/_thumbnail.html.erb
app/views/shared/ubiquity/collections/_list_collections.html.erb
app/views/shared/ubiquity/collections/_show_document_list_row.html.erb
app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
app/views/shared/ubiquity/works/_member.html.erb

Trello #[367](https://trello.com/c/PXF3QKlL)
Show generic zip icon from fontawesome in several views. Before changes, the app displays a link instead of a thumbnail:
Changes:

Icon for zip files across views

---

app/views/hyrax/homepage/_recent_document.html.erb

Follow up #192 
One column on homepage was not displaying the icon as intended.

'Latest Additions' column to display zip icon

---

app/views/hyrax/homepage/_explore_collections.html.erb
app/views/hyrax/homepage/_featured_fields.html.erb
app/views/hyrax/homepage/_recent_document.html.erb
app/views/shared/ubiquity/_thumbnail.html.erb
app/views/shared/ubiquity/collections/_list_collections.html.erb
app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb

The information we need to check if the file is a zip or not is already available in the views hence no need for the query.
If you run into this. Thanks for the work together.

avoid database query directly from view files

---

app/views/shared/ubiquity/related_exhibition_date/_related_exhibition_date.html.erb

Additional fix to: https://trello.com/c/fjHyMQ18/407-date-pickers-should-include-2019-and-2020-as-options

Add additional years to date pickers for exhibition_date view

---

app/views/hyrax/homepage/_explore_collections.html.erb
app/views/hyrax/homepage/_recent_document.html.erb
app/views/shared/ubiquity/_thumbnail.html.erb
app/views/shared/ubiquity/_thumbnail_icons.html.erb
app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
app/views/shared/ubiquity/works/_member.html.erb

Refactor how file_set is fetched in views without file_set_presenter. Also refactored thumbnail icons in two partials for some view files

Refactor how file_set is fetched in views without file_set_presenter. Also refactored thumbnail icons in two partials for some view files

---

app/helpers/multiple_metadata_fields_helper.rb
app/views/hyrax/homepage/_recent_document.html.erb
app/views/shared/ubiquity/search_display/_show_array_hash.html.erb

Resolved: https://trello.com/c/COKVGZGO/405-05-on-homepage-and-search-separate-creators-contributors-editors-with-a-semi-colon-instead-of-a-comma-also-on-search-run-all-cr

Each creators separted by semicolon and show as one liner

---

app/forms/ubiquity/additional_batch_edit.rb
app/views/records/edit_fields/_alternate_identifier.html.erb
app/views/records/edit_fields/_editor.html.erb
app/views/records/edit_fields/_related_identifier.html.erb
app/views/shared/ubiquity/alternate_identifier/_edit_form.html.erb
app/views/shared/ubiquity/alternate_identifier/_new_form.html.erb
app/views/shared/ubiquity/dates/_date_accepted.html.erb
app/views/shared/ubiquity/dates/_date_fields.html.erb
app/views/shared/ubiquity/dates/_date_published.html.erb
app/views/shared/ubiquity/dates/_date_submitted.html.erb
app/views/shared/ubiquity/editor/_edit_array_hash_form.html.erb
app/views/shared/ubiquity/editor/_new_form.html.erb
app/views/shared/ubiquity/event_date/_event_date.html.erb
app/views/shared/ubiquity/related_identifier/_edit_form.html.erb
app/views/shared/ubiquity/related_identifier/_new_form.html.erb
config/application.rb

Resolved : https://trello.com/c/NCuhUIda/412-05-bulk-edit-tool-in-dashboard-needs-more-options-of-fields-to-edit-and-fix-tate-tate
Institution as additional field has been added on the batch edit tool.

Add institution as extra term for batch editing

---

app/helpers/multiple_metadata_fields_helper.rb
app/views/shared/ubiquity/_thumbnail_icons.html.erb
app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
app/views/shared/ubiquity/file_sets/_restricted_media.html.erb
app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
app/views/shared/ubiquity/works/_member.html.erb

Resolves the following:
https://trello.com/c/EyUvCmWJ/425-01-use-default-icon-where-there-is-a-file-but-no-thumbnail-created-yet
https://trello.com/c/wBa3vjeS/431-01-default-icon-for-doc-docx-where-thumbnail-has-not-been-generated

Added additional thumbnails

---

app/helpers/multiple_metadata_fields_helper.rb
app/views/shared/ubiquity/search_display/_show_array_hash.html.erb

additional fix to creators showing on home and search page to fully resolve the below card
Resolved: https://trello.com/c/COKVGZGO/405-05-on-homepage-and-search-separate-creators-contributors-editors-with-a-semi-colon-instead-of-a-comma-also-on-search-run-all-cr

additional fix to creators showing on home and search page

---

app/helpers/ubiquity/google_tag_manager_helper.rb

allow sandbox tenant name to be set as bl in test environment

allow sandbox tenant name to be set as bl in test environment

---

config/authorities/licenses.yml

add license to avoid importer to crash for existing work
- id: http://creativecommons.org/publicdomain/mark/1.0/
term: CC0 Public Domain Mark 1.0
active: true

add license to avoid importer to crash for existing work

---

app/services/ubiquity/datacite_response.rb
config/locales/hyrax.en.yml

Resolved: https://trello.com/c/69J4bTyw/422-01-review-and-update-the-dois-which-are-listed-in-the-help-text-for-datacite-auto-population
Work done: changing license to licence to match the British spelling

change license to licence to match the British spelling

---

app/views/shared/ubiquity/_thumbnail.html.erb
app/views/shared/ubiquity/_thumbnail_icons.html.erb
app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
app/views/shared/ubiquity/collections/_list_collections.html.erb
app/views/shared/ubiquity/collections/_show_document_list_row.html.erb

Resolved: https://trello.com/c/wBa3vjeS/431-01-default-icon-for-doc-docx-where-thumbnail-has-not-been-generated-needs-amending
This fixes resolve the thumbnail alignment when using Firefox and Chrome

thumbnail alignment work for firefox and chrome

---

app/views/hyrax/homepage/_featured_fields.html.erb
app/views/hyrax/homepage/_recent_document.html.erb
app/views/shared/ubiquity/_thumbnail_featured.html.erb
app/views/shared/ubiquity/collections/_list_collections.html.erb

Resolved: https://trello.com/c/CRzci9C9/457-featured-work-shows-broken-thumbnail-for-logged-in-users
Resolved: https://trello.com/c/sFRbK0nD/463-doc-file-thumbnails-are-not-showing-on-featured-on-homepage

Featured thumbnail fix

---

app/views/shared/ubiquity/collections/_list_collections.html.erb

Resolved: https://trello.com/c/UzsqxaRq/458-fix-collection-list-page-to-show-all-the-different-thumbnail-options

change archive icon to file icon for collection list

---

app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb

Resolved: https://trello.com/c/0BdBttYX/461-default-icon-for-archives-needs-a-bit-more-horizontal-space-on-homepage
Resolved: https://trello.com/c/JZUZW5NE/462-reduce-space-to-left-of-default-icon-for-archives-on-search-results-page

fix alignment for both show and search page

---

app/views/hyrax/collections/_media_display.html.erb

Resolved : https://trello.com/c/Ecgh4hNv/459-fix-broken-thumbnail-image-when-click-on-collection-show-page-from-dashboard-and-from-home-page

Fix broken thumbnail for collections

---

app/controllers/concerns/ubiquity/breadcrumb_override.rb

Resolved: In the 'show work' page, remove the 'Home / ' link - so it just reads 'Back to search results'.
Featured on shared search card below

remove home link from breadcrumb

---

app/services/ubiquity/json_importer.rb

This is related to the work on shared search

enable json importer to populate works with account_cname

---

app/services/ubiquity/shared_search.rb
app/views/ubiquity/shared_search/_search_page_top.html.erb
app/views/ubiquity/shared_search/index.html.erb

Still addressing shared search:

added code to sanitize search input and partial to display when no search results

---

app/helpers/ubiquity/shared_search_helper.rb
app/services/ubiquity/shared_search.rb
app/views/ubiquity/shared_search/index.html.erb

Further refinement to the features in this card:
- Moved list of models to search to environment variable:
The list of models to search now come from environment variable. In the format:
SHARED_SEARCH_TYPES="Article, Book, BookContribution, ConferenceItem, Dataset, Image, Report, GenericWork"
So it is a list of strings.
- revised search display to have <hr> lines after each metadata in a work
- use default thumbnails for files under  embargo
- ensure resource_type displays correctly
- separate multiple institutions by semi-colon

hide restricted files, revise search display and move model to search to environment variable

---

app/helpers/ubiquity/file_display_helpers.rb

Resolved: https://trello.com/c/0EKy2jwn/464-ensure-that-thumbnails-are-all-displayed-centrally-aligned-and-with-equal-spacing-for-all-browsers-esp-ie11

center icons on show wok page using bootstrap

---

config/application.rb

Resolved: https://trello.com/c/MuCsFT66/489-add-google-tag-manager-to-shared-layer-pages
@fradeve the below environment variables will also need to be added on kubernetes config map.
ENV["REPOTEST_GTM_ID"]
ENV["OAR_GTM_ID"]

add gtm scripts to shared layer pages

---

app/views/ubiquity/shared_search/_search_page_top.html.erb
app/views/ubiquity/shared_search/index.html.erb

Resolved: https://trello.com/c/h3ql9tXY/491-shared-search-where-no-results-are-returned.
This pull request also contain a fix (display every line above each field: creator, institution, date_published, resource_type) obtained by repositioning the <t/body> outside the model.each loop.
File changed below: app/views/ubiquity/shared_search/index.html.erb

Shared search

---

app/views/_admin_util_links.html.erb
app/views/splash/shared_layer.html.erb

Resolved: https://trello.com/c/kOsNPQj1/487-shared-layer-remove-links-to-translation-version-of-pages

Shared layer

---

app/views/ubiquity/shared_search/_shared_search_form.html.erb

Resolved: https://trello.com/c/R5X0UK90/496-shared-search-repo-the-go-button-wraps-into-text-box-when-on-smaller-screen
Resolved: https://trello.com/c/FbAlyRb9/485-test-failed-100-beta2-58-5-shared-search-updates-to-search-box-and-homepage-text-change

Fix go button on shared search

---

app/views/_logo.html.erb
app/views/splash/shared_layer.html.erb

Resolved: https://trello.com/c/BGEzOQln/504-1-shared-search-title-in-banner-on-search-results-and-no-search-results-does-not-match-homepage

Application title

---

app/views/ubiquity/shared_search/_shared_search_thumbnail.html.erb

Resolves: https://trello.com/c/V3gnsBrU/512-fix-archivezip-icon-not-showing-on-shared-search

fix for .zip file icon not showing

---

app/views/ubiquity/shared_search/_search_page_top.html.erb

Resolves: https://trello.com/c/nodTRVM4/506-1-shared-search-show-the-total-number-of-results-in-search-results-page-assuming-more-than-0
Resolves: https://trello.com/c/Sj5NQ9yj/507-1-shared-search-in-results-make-pagination-the-same-as-on-individual-repos

Shared search pagination

---

app/controllers/ubiquity/shared_search_controller.rb
app/models/concerns/ubiquity/basic_metadata_decorator.rb
app/services/concerns/ubiquity/shared_search_util.rb
app/services/ubiquity/shared_search.rb
app/views/ubiquity/shared_search/_facet.html.erb
app/views/ubiquity/shared_search/_facet_more.html.erb
app/views/ubiquity/shared_search/_search_facet.html.erb
app/views/ubiquity/shared_search/_search_state.html.erb
app/views/ubiquity/shared_search/_shared_search_form.html.erb
app/views/ubiquity/shared_search/facet.html.erb
app/views/ubiquity/shared_search/facet.js.erb
app/views/ubiquity/shared_search/index.html.erb
config/routes.rb
lib/tasks/ubiquity_work_reindex.rake

https://trello.com/c/1l589TsD/460-7-search-across-all-repositories-from-the-shared-layer-faceted-browse
Pre-deployment task
Add the following environment variables to allow for the facet list and the number items to show before clicking more to be configurable without redeployment:
BL_SHARED_SEARCH_FACETS:   'resource_type_sim,creator_search_sim,institution_sim'
BL_SHARED_SEARCH_FACETS_SIZE:   '5'
After deployment  or post deployment run the command below for each of the tenant to reindex the whole works again because the indexing that occurred when the works were created did not include the institution metadata field as a faceted field. but now we do :
rake ubiquity_work_reindex:update['sandbox.repo-test.ubiquity.press']
rake ubiquity_work_reindex:update['sandbox2.repo-test.ubiquity.press …

add shared-search faceting

---

app/controllers/concerns/ubiquity/contact_form_controller_override.rb
app/views/shared/ubiquity/contact/_new.html.erb
config/application.rb

Resolves: https://trello.com/c/dTpXu67U/492-1-add-recaptcha-to-contact-form

contact form honey-pot implementation

---

app/controllers/ubiquity/shared_search_controller.rb
app/services/ubiquity/shared_search.rb
app/views/ubiquity/shared_search/_search_facet.html.erb
app/views/ubiquity/shared_search/_shared_search_form.html.erb

Addresses the following trello cards:
https://trello.com/c/V8ThsGkQ/102-100-beta2-58-2-enable-search-across-all-repositories-from-the-shared-layer-search-navigation
https://trello.com/c/UphxjrFD/527-shared-search-where-there-is-a-text-search-already-and-a-facet-is-added-removed-then-the-number-of-records-per-page-is-reset-to

"shared-search fix sort by relevance, and display of facet_more modal to match what is listed in facet list

---

app/services/ubiquity/shared_search.rb

https://trello.com/c/y5A6pB1h/533-add-weighting-to-metadata-fields-for-relevance-ordering-to-be-same-as-normal-search

added weighting to solr query for shared-search metadata fields inline with BL search term of pachyderm word order relevance test 

---

app/views/ubiquity/external_services/_doi_options.html.erb

Resolves:https://trello.com/c/T6nXu5fN/536-datacite-doi-minting-do-not-allow-a-user-to-go-from-mint-to-do-not-mint-for-a-work-that-has-been-sent-to-the-indexer-already-for

Add feature to disable some doi options when not available

---

app/controllers/ubiquity/fail_uploads_controller.rb
app/helpers/ubiquity/file_display_helpers.rb
config/routes.rb

Fixed: https://trello.com/c/wNbtQhj8/540-s3-download-mask-amazon-url-as-much-as-possible
S3 url masking
- Added new routes for the donwloading
- Triggered the api call in the action with the corresponding FileSet id
- Redirect the action with the s3 url

Added routes to download the file from s3 without exposing the url

---

app/views/admin/groups/edit.html.erb
app/views/hyrax/base/_form_progress.html.erb
app/views/hyrax/base/new.html.erb
app/views/ubiquity/external_services/_datacite_modal.html.erb

Modal for datacite rendering from form progress to restore correct functionality of the modal.
This pull request does not address the issue of model overlapping with institution field.

modal for datacite rendering from form progress

---

app/helpers/ubiquity/file_display_helpers.rb
app/views/shared/ubiquity/_thumbnail_featured.html.erb
app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
app/views/shared/ubiquity/file_sets/_restricted_media.html.erb

Attempt to fix an issue which causes sandbox to crash. To check for visibility we no use
`file_set_presenter.solr_document['visibility_ssi'] == "open"`

fix to allow universal viewer to work on sandbox

---

app/models/concerns/ubiquity/work_doi_lifecycle.rb

Resolved: https://trello.com/c/IvybTs67/538-datacite-when-editing-a-work-if-findable-or-registered-then-send-to-datacite-on-save-even-if-it-has-been-sent-before

allow to send updates to datacite

---

app/services/ubiquity/crossref_response.rb
app/services/ubiquity/datacite_client.rb
app/services/ubiquity/datacite_response.rb

Fixes https://trello.com/c/1KqT5Xoe/442-datacite-auto-populate-manipulate-the-incoming-licence-in-3-ways-to-match-the-licence-that-is-in-the-data-model
Added Regular Expression matching the url response with the data client URL's

Added License manipulation for crossreg and Datacite

---

app/assets/javascripts/ubiquity/datacite.js
app/services/ubiquity/crossref_response.rb
app/services/ubiquity/datacite_response.rb

Fixes: https://trello.com/c/h79c3NH8/552-crossref-pre-population-highlight-which-fields-have-been-populated-only-if-they-are-in-the-ui-deposit-form
Removed the message string module from the Response class and Integrated in the JS code in-order to check if the element is present in the DOM.

Highlight fields based on ui

---

app/views/records/edit_fields/_resource_type.html.erb

Fixes 
- https://trello.com/c/c14JiHNO/561-put-required-icon-next-to-resource-type-on-all-deposit-forms
Added required tag for the Resource Type drop down

Added required tag for the resource type

---

app/views/catalog/_index_header_list_default.html.erb
app/views/catalog/_index_list_default.html.erb
app/views/shared/ubiquity/catalog/_index_header_list_default.html.erb
app/views/shared/ubiquity/catalog/_index_list_default.html.erb

Resolves the following cards:
https://trello.com/c/pJVgZkz8/558-shared-search-show-resource-type-as-collection-in-search-results-if-it-is-a-collection
https://trello.com/c/AE4kY6XB/559-shared-search-replace-commas-between-institution-names-with-semi-colons-and-remove-and-before-last-institution

add solr relevance score and work creation to date to frontend of  new-shared-search display

---

app/forms/hyrax/generic_work_form.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/shared/ubiquity/collections/_show_collection_list.html.erb

Fixes: https://trello.com/c/J60aM5UO/563-add-book-title-in-the-generic-work-form-and-add-collection-row-in-the-display-form-for-all-the-works-if-present
- Added Book Title field in the work show page
- Added collection row in the work show page

Added book title and the collection in the display form

---

app/assets/javascripts/ubiquity/custom_required_fields.js

Fixes 
- https://trello.com/c/qf6olfvX/567-generic-work-template-journal-title-should-not-be-required
Removed the `Journal Title` as mandatory field for Generic Work

made Journal Title as required field for Article

---

app/assets/javascripts/ubiquity/external_services_modal.js
app/helpers/ubiquity/work_show_actions_helper.rb

Add a change to previous pr where now the delete message will change its content checking against the value of status code.
Resolves: https://trello.com/c/UfZCJ9y8/570-add-additional-check-to-message-validation-when-user-deletes-a-work-with-live-doi

change the check for deleting the work pop up message

---

config/locales/generic_work.en.yml

Fixes: Renaming the Generic Work Type text in the Deposit pop up modal

Renamed the generic work name in the pop up modal

---

app/models/concerns/ubiquity/all_models_virtual_fields.rb

Fixes https://trello.com/c/KD8PBgok/571-when-manipulating-the-isni-field-and-orcid-on-save-pay-attention-to-backslash-and-tabs
Added escaping special characters in the Orcid and Isni value under creator group

escaped the invalid url characters to url friendly

---

app/services/ubiquity/crossref_response.rb

Fixes https://trello.com/c/402qwrSn/413-1599-pull-metadata-from-crossref-when-provided-with-a-doi-more-dev-needed
Added Published Date for fetching the data from the `published-print key`

Cross ref url issue

---

app/helpers/application_helper.rb
app/helpers/ubiquity/file_display_helpers.rb
app/presenters/concerns/displays_image.rb
app/views/shared/ubiquity/_thumbnail_featured.html.erb
app/views/shared/ubiquity/_thumbnail_icons.html.erb
app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb

Fixes: https://trello.com/c/bcQ45rCV/577-loading-new-version-of-file-needs-to-be-possible-from-edit-file-page
Fixed the thumbnail by adding a custom helper method in the Application Helper and integrate the method in all the views.

Fixed the thumbnail issue in the file sets and the work listing

---

app/views/hyrax/dashboard/_sidebar.html.erb
config/locales/en.yml

resolved: https://trello.com/c/XiPfH9gH/390-link-is-required-to-allow-admin-navigation-from-dashboard-to-embargo-and-lease-manager

Added buttons on the sidebar to link to embargoes and leases

---

app/assets/javascripts/ubiquity/external_services_modal.js
app/helpers/ubiquity/permission_badge_helper.rb
app/views/hyrax/base/_form_progress.html.erb

Fixes:
- https://trello.com/c/uQ9uyD86/588-doi-release-after-embargo-text-in-pop-up-window-is-dependent-on-whether-you-press-the-create-and-save-draft-doi-button
- https://trello.com/c/N9YSC57R/520-15830-datacite-doi-minting-hyku-sends-message-rest-post-to-indexer-api-to-confirm-that-a-doi-needs-to-be-minted-updated

Fixed the pop up message in the datatcite doi

---

app/views/shared/ubiquity/catalog/_index_list_default.html.erb

Resolved: https://trello.com/c/mrfSfBO0/590-remove-debug-date-created-and-relevance-score-from-search-results

removed debug and relevance score from search page

---

config/authorities/resource_types.yml

Fixes the bug occurred when changed Exhibition to Exhibition item and the resource type list was not being populated. Issue raised here: 
https://trello.com/c/cIJYHtOV/352-15922-create-3-new-work-type-templates-exhibition-thesis-time-based-media

Populate resource type for Exhibition item

---

app/views/shared/ubiquity/file_sets/_actions.html.erb

Resolves: https://trello.com/c/4ObwvIBA/415-where-a-file-is-embargoed-and-a-user-does-not-have-permissions-to-take-any-actions-then-the-actions-button-should-be-hidden

 disabled action button in show work page if the user is not logged in

---

app/controllers/concerns/ubiquity/citations_export_concern.rb

Fixes : https://trello.com/c/piOtS2bg/476-v15924-5-enable-reference-management-tools-zotero-endnote-mendeley-to-read-and-export-work-metadata-via-ris-file-download
- Typo in the Keyword value

Fixed the issue in the keyword in RIF template

---

app/controllers/catalog_controller.rb
app/jobs/add_work_id_to_external_service_job.rb
app/models/concerns/ubiquity/all_models_virtual_fields.rb
app/models/concerns/ubiquity/work_doi_lifecycle.rb
app/services/ubiquity/indexer_client.rb
app/views/hyrax/base/show.html.erb

Resolves: https://trello.com/c/D1BIMe49/515-15827-doi-minting-doi-suffix-is-auto-generated-and-appended-to-prefix-saved-in-a-new-draft-doi-field-that-is-not-displayed-publi

Stop adding workid to externalservice if it exist and change update to save after adding official_url in indexer client to allow re-indexing of work

---

app/controllers/catalog_controller.rb
app/jobs/add_work_id_to_external_service_job.rb
app/models/concerns/ubiquity/all_models_virtual_fields.rb
app/models/concerns/ubiquity/track_doi_options.rb
app/models/concerns/ubiquity/work_doi_lifecycle.rb
app/services/ubiquity/indexer_client.rb
app/views/hyrax/base/show.html.erb

Resolved: https://trello.com/c/D1BIMe49/515-15827-doi-minting-doi-suffix-is-auto-generated-and-appended-to-prefix-saved-in-a-new-draft-doi-field-that-is-not-displayed-publi

Removed logs statement from the code base

---

app/views/shared/ubiquity/works/_member.html.erb

Fixes https://trello.com/c/bcQ45rCV/577-v15924-loading-new-version-of-file-needs-to-be-possible-from-edit-file-page-revert-before-release-to-live
Fixed the label in the file display page

Displaying the file title instead of file label in the show page

---

app/models/concerns/ubiquity/all_models_virtual_fields.rb
app/services/ubiquity/indexer_client.rb

Fixed: https://trello.com/c/fTpzGNZV/450-v15929-update-filters-to-include-facet-by-file-availability-switched-off
This pull request fixed the the error with ActiveFedora when trying to run the rake task for file availability faceting

fixed the Active fedora error for the rake task

---

app/models/concerns/ubiquity/update_shared_index.rb
app/models/concerns/ubiquity/work_doi_lifecycle.rb
lib/tasks/ubiquity_index_file_availability_facet.rake

####### Run it with 
rake "ubiquity_index_file_availability_facet:update_specific_model[library.localhost,  generic_work]"
rake ubiquity_index_file_availability_facet:update_specific_model[library.localhost,  generic_work]
fails with 
Don't know how to build task 'ubiquity_index_file_availability_facet:update_specific_model[library.localhost,' (see --tasks)

allow file_availability rake task to be run per model by passing in the model and tenant name

---

app/forms/hyrax/article_form.rb

Fixes: https://trello.com/c/U1AjYOyX/610-missing-language-field-in-article-deposit-form

Add language missing field in article form

---

app/indexers/file_set_indexer.rb
app/models/concerns/ubiquity/update_shared_index.rb
app/services/ubiquity/shared_index_solr_service_wrapper.rb

return object or empty hash in rescue when block  to_solr fails in file_set indexer when running  file_availability rake task

---

app/indexers/file_set_indexer.rb

return empty hashif object is nil in rescue when block  to_solr fails in file_set indexer when running file_availability rake task

---

app/services/ubiquity/json_importer.rb

https://trello.com/c/ny0pVK4C/584-v15924-allow-json-importer-to-update-records-based-on-keys-in-imported-csv-was-reverted-before-release-1600-needs-un-reverting
1.  You replace the path to any file in the hash with a local file path or give it no file.
2. Use you local tenant name and domain
1. Use either Nms, Sandbox, Sample or Stuff which are 4  constants holding similar json to what we expect from the Python Importer. These constants are defined here:
https://github.com/ubiquitypress/hyku/blob/test/app/services/ubiquity/queue_import.rb#L100-L240
Start Rails and Sidekiq . Then in Rails console do the following:
k = Nms
QueueImport.upload(k)
That will create a job via the importer
Then to update the just the title of the work created via NMS use this new hash for a partial update
ku = …

restore ability to for partial update of works with only selected keys via the json-importer

---

app/controllers/catalog_controller.rb
app/helpers/ubiquity/date_change_helper.rb
app/indexers/shared_indexer.rb
app/services/ubiquity/parse_date.rb
lib/tasks/ubiquity_resave_records.rake

https://trello.com/c/EkYxRi1X/137-5-sort-search-results-by-year-published-only
rake ubiquity_resave_records:all_exempt_collections['library.localhost']

add ability to sort search results by date_published using year only

---

app/models/concerns/ubiquity/track_doi_options.rb

Fixes: https://trello.com/c/HQZcIqPK/618-1614bad-doi-format-makes-hyku-crash-changes-needed-to-make-hyku-correct-the-format
Removed chopping of the last character of url for special characters

Fixed the issue in chopping the url

---

app/controllers/concerns/ubiquity/citations_export_concern.rb

Fixes: https://trello.com/c/piOtS2bg/476-v1612-v15924-5-enable-reference-management-tools-zotero-endnote-mendeley-to-read-and-export-work-metadata-via-ris-file-download
Fixed the issue with the Audio resource type

Fixed the sound resource type issue in the rif template

---

app/services/ubiquity/datacite_client.rb

Fixes: https://trello.com/c/QI9QAOHe/608-support-old-style-crossref-dois-in-metadata-lookup-deposit-form-auto-fill

Added parsing for url in datacite

---

app/views/shared/ubiquity/file_sets/_restricted_media.html.erb

Resolves: https://trello.com/c/ZmRtstLE/421-2-download-button-at-top-of-show-work-page-where-there-is-a-thumbnail-should-be-changed-to-contact-for-file

Download button large files

---

app/indexers/shared_indexer.rb
app/models/solr_document.rb
app/services/ubiquity/fetch_tenant_url.rb

Fixes https://trello.com/c/gemPv5Tz/165-16116-oai-pmh-harvesting-is-in-place
- Added tenant url in the OAI template
Do run the below rake task to display the url
`rake ubiquity_resave_records:all_exempt_collections['sandbox.repo-test.ubiquity.press']`

Oai pmh new changes

---

app/services/ubiquity/fetch_tenant_url.rb

Fixes : https://trello.com/c/gemPv5Tz/165-16117-16116-oai-pmh-harvesting-is-in-place
Fixed OAI-PMH tenant url for the live tenants

Removing the 3000 port in the tenant url address

---

app/services/ubiquity/csv_generator.rb

https://trello.com/c/8QuJT627/411-161171615v15924-make-improvements-to-export-a-csv-file-of-the-repository-metadata

revert changes that caused wrong ordering of json in  csv column headers

---

app/indexers/exhibition_item_indexer.rb
app/indexers/thesis_or_dissertation_indexer.rb
app/indexers/time_based_media_indexer.rb
app/services/ubiquity/fetch_tenant_url.rb

Fixes https://trello.com/c/gemPv5Tz/165-16117-16116-oai-pmh-harvesting-is-in-place
Fixed the issue with the Time Based Media and the broken link in the oai-pmh. 
We need to re-run the rake task for the following specific models
> ExhibitionItem
> ThesisOrDissertation
> TimeBasedMedia
> BookContribution
> GenericWork
> ConferenceItem

Fixed the issue with the oai-pmh

---

app/mailers/work_report_mailer.rb
app/services/ubiquity/fetch_mailer_report_data.rb

Refactored the WorkReportMailer class so instance variables `@data  and  @summary_data `  :
can now use the `Ubiquity::FetchMailerReportData` class and fetch the data calling the class method `self.method fetch_data` like so:
```
@data = Ubiquity::FetchMailerReportData.fetch_data(date_period)
@summary_data = Ubiquity::FetchMailerReportData.fetch_data('[* TO *]')
```

refactoring mailer code

---

app/controllers/ubiquity/account_settings_controller.rb
app/models/concerns/ubiquity/account_self_join_association.rb
app/models/concerns/ubiquity/update_shared_index.rb
app/views/ubiquity/account_settings/edit.html.erb
app/views/ubiquity/account_settings/index.html.erb

https://trello.com/c/EQuv9SXH/605-v1602-enable-or-disable-shared-search-from-the-ui-account-settings-set-to-false-to-exempt-a-tenants-record-from-being-indexed-to

shared-search now uses db settings to determine tenants to exempt from shared-search

---

docker-entrypoint.sh
spec/mailers/previews/work_report_mailer_preview.rb

Refactored mailer review to use ENV variables as follows: 
```
email = ENV['SMTP_USERNAME']
tenant = ENV['DEVELOPER_PREVIEW_EMAIL_HOST_NAME']
```

refactor emailer preview to use ENV variables

---

app/views/hyrax/dashboard/works/_list_works.html.erb

The variable presenter was missing in the call to the partial, hence the broken link

passed the presenter as variable to the partial

---

app/controllers/api/v1/tenant_controller.rb
app/models/concerns/ubiquity/account_self_join_association.rb
app/views/api/v1/tenant/_tenant.json.jbuilder
app/views/api/v1/tenant/index.json.jbuilder
app/views/api/v1/tenant/show.json.jbuilder

This PR implements the content block and site to be available form the json at the `/api/v1/tenant/` endpoint.

add tenant endpoint with site and content block information

---

app/models/file_set.rb

This PR prevents an api post to the python importer when upoading a file to hyku, if the request comes form local host

add fix to prevent posting to api importer if cname is localhost

---

app/controllers/api/v1/work_controller.rb

fixes manifest error by assigning     request.env["HTTP_HOST"]= account_cname

refactor manifest error to assign the host to account_cname

---

app/controllers/api/v1/work_controller.rb
app/services/ubiquity/api_utils.rb
app/views/api/v1/work/_work.json.jbuilder

This PR removes files and collections from all the endpoint other than /work/id

files and collection only available at single work endpoint

---

app/controllers/api/v1/highlights_controller.rb

This Pr fixes a bug introduced with the previous PR below:
```
https://github.com/ubiquitypress/hyku/pull/609
```
The whole data obj is now correctly returned

ensure the whole data obj is returned to retrieve the featured works

---

app/services/ubiquity/api_utils.rb

This PR catches a previous error thrown when rendering collections

error handling for collections

---

app/views/api/v1/highlights/index.json.jbuilder

This PR adds the a featured_order array to the highlights endpoint so the the order of the featured work can be arranged from the front-end

passing the featured order to highlights end-point

---

app/views/shared/ubiquity/contributor/_contributor_form_fields.html.erb

Includes fix for removing "contributor" as  mandatory field in all deposit forms. These fixes make changes to the local.env which will need to be updated on deployment.

Fix for removing "contributor" as  mandatory field in all deposit forms

---

app/helpers/ubiquity/settings_helper.rb
app/views/hyrax/dashboard/collections/_list_works.html.erb
app/views/hyrax/dashboard/works/_list_works.html.erb
app/views/hyrax/my/works/_list_works.html.erb
app/views/shared/ubiquity/collections/_list_collections.html.erb
app/views/shared/ubiquity/collections/_show_document_list_row.html.erb
app/views/shared/ubiquity/dashboard/_list_works.html.erb

Requires new settings in the environment variables eg if the tenant subdomain is live and demo, we will have:
"redirect_show_link": {
"demo": {"url": "https://demo.pacific.us-frontend.ubiquityrepository.website"},
"live": {"url": "https://live.pacific.us-frontend.ubiquityrepository.website"}
}

redirect work show page to react frontend

---

app/models/concerns/ubiquity/update_shared_index.rb
app/services/ubiquity/api_utils.rb

saving or updating a collection should not trigger callbacks to re-index child works

---

app/helpers/ubiquity/settings_helper.rb
app/services/ubiquity/parse_tenant_work_settings.rb
app/views/hyrax/base/_form_rendering.html.erb
app/views/hyrax/base/_guts4form.html.erb
app/views/shared/ubiquity/works/_adpated_guts4form.html.erb
app/views/shared/ubiquity/works/_form_member_of_collections.html.erb
app/views/shared/ubiquity/works/_form_metadata.html.erb
app/views/shared/ubiquity/works/_guts4form.html.erb
app/views/shared/ubiquity/works/_non_fedora_form_member_of_collections.html.erb

Requires the addition to TENANT_SETTINGS environment variable the key and value below:
"hide_form_relationship_tab": true

move relationship in forms from a tab into the main form for pacific

---

app/helpers/ubiquity/settings_helper.rb
app/models/concerns/ubiquity/email_format.rb
app/services/ubiquity/parse_tenant_work_settings.rb

In the interests of keeping PR's small I am putting in a PR now before I replace all the methods. 
I couldn't get the helpers into the email_validator class, feel free to refactor.
This PR:
1. Moves Email validation into per account settings
2. Removes the redirect show link setting
3. Adds methods to look for a default setting if non is found in the per account setting
The next PR will refactor all parts of the code to use either the check_for_setting or check_for_nested_setting for pulling data from the hash

Repo 634/further settings refactor

---

app/forms/ubiquity/all_forms_shared_behaviour.rb
app/models/concerns/ubiquity/all_models_virtual_fields.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/records/edit_fields/_funder.html.erb
app/views/shared/ubiquity/funder/_edit_array_hash_form.html.erb
app/views/shared/ubiquity/funder/_new_form.html.erb
app/views/shared/ubiquity/funder/_show.html.erb
app/views/shared/ubiquity/funder/_show_array_hash.html.erb

I- n the deposit form, use Java script to select a Funder (this is no longer a controlled picklist of approx 40 funders, but is instead an auto-suggesting field which is based on the Crossref Funder Registry of over 21,000 funders).
- When a funder has been selected, then the ISNI and ROR IDs are populated from either a local copy of the ROR registry or via the ROR API (this is a registry of over 97,000 research organisations).
- Leave a free text field for Funder name non included in the registry
- Use Funder DOI from CrossRef as Funder ID
- Allow Multiple Funders
- Use both ISNI + ROR for each Funder in separate fields

Added funder group fields and form templates

---

app/assets/javascripts/ubiquity/orcid_isni_validation.js

The problem was that after setting a contributor to Organisational and filling in the name and isni the check on line 72 failed and the check on 75 passed and since family name and given name are present but empty it went on to execute 78.  This change skips the check on 75 as it should when the type is Organisational.

Only mark personal fields mandatory when type dropdown is set to Personal

---

app/views/shared/ubiquity/funder/_edit_array_hash_form.html.erb

Because the CSS classes were named differently the funder autocomplete callback wasn't able to set the ROR and ISNI as was working on the new form. See https://github.com/ubiquitypress/hyku/blob/test/app/assets/javascripts/ubiquity/funder_autocomplete_callback.js#L22-L23
@BertZZ I'm not able to test this change since it is server-side, but I'm pretty confident in it.

Add underscore so CSS class names match those used in new form

---

app/helpers/ubiquity/importer_link_helper.rb

I hard-coded instead of using the `S3_API_WRAPPER_URL` ENV variable just because I don't know enough to feel confident that that is the correct ENV variable and that it won't change for another reason later breaking the links.

Default to Pacific importer instead of BL's

---

app/jobs/ubiquity_cleanup_uploads_job.rb

Bad syntax with `begin`
`File.delete` is a real method while `File.rm` isn't
Use less helpful `exception.to_s` because Ldp::Gone doesn't work well with `full_message`
Added comment about future work
With these changes, I was able to manually run the job on repo-test.ubiquity.press and it removed ~7G of files (out of 11G):
```
I, [2020-10-26T20:34:22.176124 #4118]  INFO -- : [ActiveJob] [UbiquityCleanupUploadsJob] [64fe6655-8f06-4e92-b413-aef2f18a78be] Performed UbiquityCleanupUploadsJob (Job ID: 64fe6655-8f06-4e92-b413-aef2f18a78be) from Sidekiq(default) in 691399.29ms
```

Fix issues with Uploads cleanup job

---

app/models/concerns/ubiquity/all_models_virtual_fields.rb

When trying to import contributors without a contributor the code was dealing with the contributor block by making the value a string of ```"contributor"=>["\"\""]```
This PR guards against a blank string slipping through into this method

Gurads against blank data_hash value

---

app/mailers/hyku_mailer.rb

Force https links for all urls generated by devise emails.
