ubiquitypress/hyku

- app/forms/hyrax/report_form.rb
- app/models/report.rb
Trello card [#2655](https://trello.com/c/lC1NNLVK)
_Not the full card specs, more fields to be created_
_See PR #20_
> Report template: new core metadata fields

- app/forms/hyrax/dataset_form.rb
- app/models/dataset.rb
Trello card [#2644](https://trello.com/c/T2MevzZ3)
_Not the full card specs, more fields to be created_ 
_See PR #20_
> Dataset template: core metadata fields

- app/forms/hyrax/conference_item_form.rb
- app/models/conference_item.rb
Trello card [#2666](https://trello.com/c/R8L08tdz)
_Not the full card specs, more fields to be created_ 
_See PR #20_
> Conference Item template: new core metadata fields

- app/forms/hyrax/book_contribution_form.rb
- app/models/book_contribution.rb
Trello card [#2663](https://trello.com/c/XyUKX4vX)
_Not the full card specs, more fields to be created_ 
_See PR #20_
> Book Contribution template: core metadata fields

- app/forms/hyrax/book_form.rb
- app/models/book.rb
Trello card [#2662](https://trello.com/c/ITjb2hGv)
_Not the full card specs, more fields to be created_ 
_See PR #20_
> Book template: core metadata fields applied

- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/views/hyrax/base/_attribute_rows.html.erb
Completes work merged in PR #27
> Missing attribute row, and facetable indexing

- config/authorities/licenses.yml
Trello card [#2704](https://trello.com/c/6xFuTuFE)
> Change options in Licence field

- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/models/concerns/ubiquity/shared_metadata.rb
- app/models/journal_article.rb
Trello card [#2705](https://trello.com/c/s2oCcfyV)
> Make requested metadata fields single value

- app/assets/javascripts/application.js
Test site fix for for application.js: missing `/`
> Added double slash to require_tree in application.js

- app/assets/javascripts/application.js
Test site fix for for application.js
> Restore application.js to original

- app/helpers/journal_articles_helper.rb
- app/views/generic_works/ubiquity/contributor/_edit_array_form.html.erb
- app/views/generic_works/ubiquity/contributor/_edit_array_hash_form.html.erb
- app/views/generic_works/ubiquity/contributor/_edit_hash_form.html.erb
- app/views/generic_works/ubiquity/contributor/_new_form.html.erb
- app/views/journal_articles/ubiquity/contributor/_edit_array_hash_form.html.erb
- app/views/journal_articles/ubiquity/contributor/_new_form.html.erb
- app/views/journal_articles/ubiquity/creator/_edit_array_hash_form.html.erb
- app/views/journal_articles/ubiquity/creator/_edit_form.html.erb
- app/views/shared/ubiquity/_editor_js.html.erb
- app/views/shared/ubiquity/contributor/_contributor_js.html.erb
- app/views/shared/ubiquity/creator/_creator_js.html.erb
Several bug fixes for Journal Article template.
> Linked creator metadata

- app/views/books/ubiquity/contributor/_edit_array_hash_form.html.erb
- app/views/books/ubiquity/contributor/_edit_hash_form.html.erb
- app/views/books/ubiquity/contributor/_new_form.html.erb
- app/views/books/ubiquity/editor/_edit_array_hash_form.html.erb
- app/views/books/ubiquity/editor/_edit_hash_form.html.erb
- app/views/books/ubiquity/editor/_new_form.html.erb
- app/views/generic_works/ubiquity/contributor/_edit_array_form.html.erb
- app/views/generic_works/ubiquity/contributor/_edit_array_hash_form.html.erb
- app/views/generic_works/ubiquity/contributor/_edit_hash_form.html.erb
- app/views/generic_works/ubiquity/contributor/_new_form.html.erb
- app/views/generic_works/ubiquity/editor/_edit_array_hash_form.html.erb
- app/views/generic_works/ubiquity/editor/_new_form.html.erb
- app/views/journal_articles/ubiquity/contributor/_edit_array_hash_form.html.erb
- app/views/journal_articles/ubiquity/contributor/_new_form.html.erb
- app/views/shared/ubiquity/_editor_js.html.erb
- app/views/shared/ubiquity/contributor/_contributor_js.html.erb
Hooks up JavaScript logic for Book template `contributor` and `editor` views.
> Book multi fields

- app/views/hyrax/base/_when_no_file.html.erb
Fixes Trello [#191](https://trello.com/c/phRHb7nP)
> Fix nil edit_access error

- app/forms/hyrax/book_contribution_form.rb
- app/forms/hyrax/book_form.rb
- app/forms/hyrax/conference_item_form.rb
- app/forms/hyrax/dataset_form.rb
- app/forms/hyrax/report_form.rb
Fixes Trello [#230](https://trello.com/c/tRZpeDhJ)
> Add "Official url" field where it was missing

- app/views/shared/ubiquity/alternate_identifier/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/alternate_identifier/_new_form.html.erb
- app/views/shared/ubiquity/contributor/_contributor_js.html.erb
> Fix copy-pasta accident which broke the remove button

- app/helpers/multiple_metadata_fields_helper.rb
- app/models/concerns/ubiquity/all_models_virtual_fields.rb
- app/models/concerns/ubiquity/editor_metadata_model_concern.rb
- app/views/shared/ubiquity/contributor/_show_array_hash.html.erb
- app/views/shared/ubiquity/contributor/_show_hash.html.erb
- app/views/shared/ubiquity/creator/_show_array_hash.html.erb
- app/views/shared/ubiquity/editor/_show_array_hash.html.erb
Stop display of empty parenthesis when no json data
> stop display of empty parenthesis when no json data 

- app/controllers/catalog_controller.rb
- app/forms/hyrax/book_contribution_form.rb
- app/forms/hyrax/book_form.rb
- app/forms/hyrax/conference_item_form.rb
- app/forms/hyrax/dataset_form.rb
- app/forms/hyrax/generic_work_form.rb
- app/forms/hyrax/journal_article_form.rb
- app/forms/hyrax/report_form.rb
- app/models/dataset.rb
- app/models/solr_document.rb
- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- config/locales/dataset.en.yml
- config/locales/journal_article.en.yml
Removed "subject" and "source" fields,
Changed "publisher" help text.
> Added "version" metadata field to "Dataset" templates,

- app/controllers/catalog_controller.rb
- app/forms/hyrax/book_contribution_form.rb
- app/forms/hyrax/book_form.rb
- app/forms/hyrax/generic_work_form.rb
- app/forms/hyrax/report_form.rb
- app/models/concerns/ubiquity/shared_metadata.rb
- app/models/solr_document.rb
- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- config/locales/book.en.yml
Add ISBN field to "Book", "Book contribution", "Report" and "Generic work" templates.
> New metadata field: ISBN

- app/controllers/catalog_controller.rb
- app/helpers/ubiquity/solr_search_display_helpers.rb
Trello [#2703](https://trello.com/c/0Hi8SqVY)
Follow up PR #30
> Search results display human readable resource type

- app/forms/hyrax/generic_work_form.rb
Trello cards [#225](https://trello.com/c/b7Dfa5pa) and [#235](https://trello.com/c/z8wTsdgF)
> Amend required fields for Generic Work form

- app/forms/hyrax/book_contribution_form.rb
- config/locales/book_contribution.en.yml
- config/locales/conference_item.en.yml
Help text varies between "Book contribution" and "Conference item".
Trello [#238](https://trello.com/c/rsOXhY6X)
> Added "Book title" field to "Book contribution" form;

- app/services/resource_types_service.rb
- config/authorities/licenses.yml
- config/authorities/resource_types.yml
Trello [#190](https://trello.com/c/ZOA45x1x)
> Fixes 'key not found: term' error on search result display

- app/forms/ubiquity/all_forms_shared_behaviour.rb
- app/helpers/multiple_metadata_fields_helper.rb
- app/views/records/edit_fields/_contributor.html.erb
- app/views/records/edit_fields/_creator.html.erb
- app/views/records/edit_fields/_title.html.erb
- app/views/shared/ubiquity/contributor/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/contributor/_new_form.html.erb
- app/views/shared/ubiquity/creator/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/creator/_new_form.html.erb
Fix inability to add or create new collection
> fix inability to add or create new collection

- app/forms/hyrax/generic_work_form.rb
- app/models/concerns/ubiquity/shared_metadata.rb
- app/models/dataset.rb
> "Version" metadata field in "Generic Work"

- app/controllers/catalog_controller.rb
Trello [#253](https://trello.com/c/2GjBzAWm)
> Comment out unwanted search filters

- app/controllers/catalog_controller.rb
Trello [#253](https://trello.com/c/YRmPpTaL)
> Commented out unwanted fields in search result; added "Collection"

- app/controllers/catalog_controller.rb
- app/helpers/ubiquity/solr_search_display_helpers.rb
- app/views/catalog/_index_list_default.html.erb
- app/views/hyrax/base/_attribute_rows.html.erb
- app/views/shared/ubiquity/contributor/_show.html.erb
- app/views/shared/ubiquity/contributor/_show_array_hash.html.erb
- app/views/shared/ubiquity/creator/_show.html.erb
- app/views/shared/ubiquity/creator/_show_array_hash.html.erb
- app/views/shared/ubiquity/editor/_show.html.erb
- app/views/shared/ubiquity/editor/_show_array_hash.html.erb
- app/views/shared/ubiquity/search_display/_show_array_hash.html.erb
Fixes https://trello.com/c/rRY03BeK/283-fix-display-of-json-field-on-search-page
> fix display of json on search result page. That is the main content

- app/presenters/hyrax/homepage_presenter.rb
- app/views/shared/_footer.html.erb
Trello #[57](https://trello.com/c/Q3qgSjP7)
and #[58](https://trello.com/c/qMfxfwVC)
In `app/presenters/hyrax/homepage_presenter.rb`, see lines 18-24.
> Homepage - remove "Share your work" button, move "Terms of Use" to footer

- app/views/hyrax/base/_representative_media.html.erb
- app/views/hyrax/homepage/_explore_collections.html.erb
- app/views/hyrax/homepage/_recent_document.html.erb
Stop the display of default icons on work show page.
> Fix work thumbnail icon

- app/models/concerns/ubiquity/all_models_virtual_fields.rb
- app/models/concerns/ubiquity/editor_metadata_model_concern.rb
Restore nil check to json fields in  before_save
> restore nil check to json fields in before save

- app/views/records/edit_fields/_resource_type.html.erb
> Pre-select existing resource_type if there is one

- app/assets/stylesheets/hyrax.scss
- app/assets/stylesheets/ubiquity.scss
Trello #[289](https://trello.com/c/h7e7ZTqX)
> Reduce font size of Work Title

- app/views/shared/ubiquity/alternate_identifier/_show_array_hash.html.erb
- app/views/shared/ubiquity/related_identifier/_show_array_hash.html.erb
Trello #[279](https://trello.com/c/QjTpheiN)
> Remove commas

- app/helpers/multiple_metadata_fields_helper.rb
Added ability to handle url path without a uri scheme
> Added ability to handle url path without a uri scheme

- app/controllers/concerns/ubiquity/breadcrumb_override.rb
- app/controllers/hyrax/shared_behaviors_controller.rb
Trello #[204](https://trello.com/c/bGRDwbT3)
For logged in users:
Not logged in:
> Do not show the breadcrumb trail for non-logged-in users

- app/views/shared/ubiquity/contributor/_show_array_hash.html.erb
- app/views/shared/ubiquity/creator/_show_array_hash.html.erb
- app/views/shared/ubiquity/editor/_show_array_hash.html.erb
- app/views/shared/ubiquity/search_display/_show_array_hash.html.erb
Added line break between data from json field in individual work display
> Added line break between data from json field in individual work display

- app/assets/stylesheets/ubiquity.scss
Trello #[251](https://trello.com/c/9OKZBdto)
> Change font of metadata labels in search results page

- config/locales/article.en.yml
- config/locales/book_contribution.en.yml
- config/locales/conference_item.en.yml
- config/locales/dataset.en.yml
- config/locales/report.en.yml
for "Issue", "Resource type" and "Publisher" fields.
Trello cards #[194](https://trello.com/c/rJ4rlwTs), #[236](https://trello.com/c/tTfU8qUI), #[243](https://trello.com/c/P0PtwG3d)
> Changes in help text for metadata submission form,

- app/views/records/edit_fields/_resource_type.html.erb
> Fix 'Resource Type' - in custom partial (not vocabulary)

- app/assets/stylesheets/ubiquity.scss
Trello #[249](https://trello.com/c/vIBNZyaH) and #[250](https://trello.com/c/Fs9hG4Qw)
> Remove banner-image CSS overlays

- config/authorities/institution.yml
Trello #[299](https://trello.com/c/3EtRMkr8)
> Correct naming of NMS

- app/views/shared/ubiquity/search_display/_show_array_hash.html.erb
Fixes spacing issue in search result page, between last name and first name.
Follow up on Trello #[207](https://trello.com/c/DsHzxNI9)
> Remove unwanted spaces

- app/helpers/application_helper.rb
- app/helpers/multiple_metadata_fields_helper.rb
- app/models/concerns/ubiquity/all_models_virtual_fields.rb
- app/models/concerns/ubiquity/editor_metadata_model_concern.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- app/views/records/edit_fields/_contributor.html.erb
- app/views/records/edit_fields/_creator.html.erb
- app/views/records/edit_fields/_editor.html.erb
- app/views/shared/ubiquity/alternate_identifier/_edit_form.html.erb
- app/views/shared/ubiquity/related_identifier/_edit_form.html.erb
- lib/tasks/json_array.rake
Fixes https://trello.com/c/0QcsuaJR/287-05-contributor-displays-in-front-end-even-when-empty-check-spec-re-test
> Ensure json data with only default keys are not saved. Also fixes empty contributor displaying

- lib/importer/factory.rb
- lib/importer/factory/article_factory.rb
- lib/importer/factory/book_contribution_factory.rb
- lib/importer/factory/book_factory.rb
- lib/importer/factory/conference_item_factory.rb
- lib/importer/factory/dataset_factory.rb
- lib/importer/factory/report_factory.rb
Trello #[310](https://trello.com/c/WOjHfGAT)
Added to `Article`, `Book`, `BookContribution`, `ConferenceItem`, `Dataset`, `Report`.
> Add importer factories for each work type

- lib/active_job_tenant.rb
> removed HoneyBadger from ActiveJob

- app/actors/hyrax/actors/article_actor.rb
- app/actors/hyrax/actors/book_actor.rb
- app/actors/hyrax/actors/book_contribution_actor.rb
- app/actors/hyrax/actors/conference_item_actor.rb
- app/actors/hyrax/actors/dataset_actor.rb
- app/actors/hyrax/actors/generic_work_actor.rb
- app/actors/hyrax/actors/image_actor.rb
- app/actors/hyrax/actors/report_actor.rb
- app/actors/hyrax/actors/ubiquity_shared_actor.rb
- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/models/concerns/ubiquity/shared_metadata.rb
Error was: `You attempted to set the property 'journal_title' of  to an enumerable value. However, this property is declared as singular. (ArgumentError)`
> Fix ActiveFedora ArgumentError on metadata fields set to `multiple: false`

- app/assets/stylesheets/ubiquity.scss
- app/views/hyrax/homepage/_home_content.html.erb
- config/locales/hyrax.en.yml
Trello cards #[318](https://trello.com/c/yu45GP96), #[321](https://trello.com/c/46CgOZjB), #[319](https://trello.com/c/3Z5wN278)
> fine-tune homepage display

- app/views/hyrax/homepage/_explore_collections.html.erb
Trello #[320](https://trello.com/c/7co73RYL)
> Homepage collection column message when there are no collections to display

- app/controllers/catalog_controller.rb
- app/forms/hyrax/article_form.rb
- app/forms/hyrax/book_contribution_form.rb
- app/forms/hyrax/book_form.rb
- app/forms/hyrax/conference_item_form.rb
- app/forms/hyrax/dataset_form.rb
- app/forms/hyrax/generic_work_form.rb
- app/forms/hyrax/image_form.rb
- app/forms/hyrax/report_form.rb
- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/models/solr_document.rb
- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- config/locales/article.en.yml
Trello #[317](https://trello.com/c/cfIjf69K/317-support-new-metadata-field-for-library-of-congress-classification)
>  New metadata field: Library of Congress Classification

- app/assets/stylesheets/ubiquity.scss
- app/forms/ubiquity/all_forms_shared_behaviour.rb
- app/forms/ubiquity/editor_metadata_form_behaviour.rb
- app/helpers/multiple_metadata_fields_helper.rb
- app/views/records/edit_fields/_resource_type.html.erb
- app/views/records/edit_fields/_title.html.erb
- app/views/shared/ubiquity/contributor/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/contributor/_new_form.html.erb
- app/views/shared/ubiquity/creator/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/creator/_new_form.html.erb
- app/views/shared/ubiquity/editor/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/editor/_new_form.html.erb
Resolved the Trello card below:
https://trello.com/c/6joEmfb0/309-support-new-metadata-field-for-institutional-relationship-for-creator-contributor-editor
> Added institutional relationship asa sub field to the  json fields

- app/views/hyrax/base/_attribute_rows.html.erb
- config/locales/hyrax.en.yml
> Correct label for LCC

- config/authorities/resource_types.yml
Trello #[334](https://trello.com/c/gc71cGxI)
> Add 'Dissertation' resource_type to GenericWork

- app/controllers/catalog_controller.rb
- app/forms/hyrax/conference_item_form.rb
- app/models/concerns/ubiquity/shared_metadata.rb
- app/models/solr_document.rb
- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
Trello #[340](https://trello.com/c/nSAjd8R5)
> New metadata field: 'Event location'

- app/assets/stylesheets/ubiquity.scss
- app/controllers/hyrax/shared_behaviors_controller.rb
- app/forms/ubiquity/all_forms_shared_behaviour.rb
- app/helpers/application_helper.rb
- app/models/concerns/ubiquity/note.rb
- app/views/hyrax/base/_form_notes.html.erb
- app/views/hyrax/base/_guts4form.html.erb
- app/views/shared/ubiquity/_mailboxer_note.html.erb
- config/locales/hyrax.en.yml
- config/locales/hyrax.fr.yml
- config/locales/hyrax.it.yml
As specc'ed in Trello #[168](https://trello.com/c/E2HEuxcG)
> New 'Notes' tab on Work submission form

- app/models/concerns/ubiquity/shared_metadata.rb
- app/services/hyrax/form_metadata_service.rb
- app/views/records/edit_fields/_rights_statement.html.erb
'Article number' made single,
'Rights statement' made multiple.
Trello #[184](https://trello.com/c/pd8kLCdR)
> Adjustments to metadata fields:

- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/views/hyrax/base/_attribute_rows.html.erb
Trello #[344](https://trello.com/c/N90wU3lj)
> Change metadata field from single to multi - 'Project name'

- app/views/hyrax/base/_ubiquity_metadata.html.erb
- app/views/hyrax/base/show.html.erb
Trello #[214](https://trello.com/c/sbmMdjyk)
> Remove 'Relationships' header in Work show page

- config/authorities/funder.yml
Trello #[341](https://trello.com/c/R9RrMa8f)
> Add new funder to picklist

- config/authorities/contributor_group.yml
Trello #[337](https://trello.com/c/B9lZoHNt)
> Additional contributor types

- app/views/hyrax/dashboard/works/_default_group.html.erb
- app/views/hyrax/dashboard/works/_list_works.html.erb
- app/views/hyrax/my/_search_header.html.erb
Trello #[348](https://trello.com/c/07bt13Rx)
- Add checkboxes,
- Enable batch actions on `/dashboard/works` as on `/dashboard/my/works` : `"Edit selected"`, `"Delete selected"`, `"Add to Collection"`.
> Allow Admin users to add works created by any submitter to any Collection

- app/helpers/application_helper.rb
- app/helpers/ubiquity/date_change_helper.rb
- app/views/shared/ubiquity/_date_accepted.html.erb
- app/views/shared/ubiquity/_date_published.html.erb
- app/views/shared/ubiquity/_date_submitted.html.erb
- app/views/shared/ubiquity/related_exhibition_date/_related_exhibition_date.html.erb
Resolved invalid date errors with related_exhibition_date
> fix invalid date errors with related_exhibition_date

- app/models/concerns/ubiquity/all_models_virtual_fields.rb
- app/services/ubiquity/parse_date.rb
> Ensure present? is used

- app/models/concerns/ubiquity/all_models_virtual_fields.rb
Trello #[364](https://trello.com/c/nSmuIg3l)
following up on #163 and #165
> Support CSV import for dates array

- app/views/shared/ubiquity/event_date/_event_date.html.erb
> Fix invalid date error on Edit form

- app/helpers/ubiquity/date_change_helper.rb
- app/models/concerns/ubiquity/all_models_virtual_fields.rb
- app/views/shared/ubiquity/_date_accepted.html.erb
- app/views/shared/ubiquity/_date_published.html.erb
- app/views/shared/ubiquity/_date_submitted.html.erb
- app/views/shared/ubiquity/event_date/_event_date.html.erb
- app/views/shared/ubiquity/related_exhibition_date/_related_exhibition_date.html.erb
Trello #[369](https://trello.com/c/lH0Otqf7)
> Refactor all date fields as Strings for consistency

- app/forms/hyrax/generic_work_form.rb
Trello #[373](https://trello.com/c/9RhgkG2r)
> Add event_title, event_location and event_date fields to Generic Work

- app/views/shared/ubiquity/contributor/_edit_array_hash_form.html.erb
Fixes Trello #[379](https://trello.com/c/dwRBYC2X)
> Correct order of Contributor family_name, given_name on Edit form

- app/services/ubiquity/datacite_response.rb
- app/views/records/edit_fields/_doi.html.erb
- app/views/shared/ubiquity/_datacite_js.html.erb
auto populate doi from datacite api call
> auto populate doi from datacite api call

- .gitignore
- app/views/hyrax/base/_items.html.erb
- app/views/shared/ubiquity/works/_items.html.erb
- app/views/shared/ubiquity/works/_member.html.erb
show when embargo and lease will end on work page
> show when embargo and lease will end on work page

- app/views/shared/ubiquity/_datacite_js.html.erb
Fix for datacite creator not working well on IE11-js
https://trello.com/c/MgpHzLCz/5-access-the-repository-in-a-supported-browser-chrome-firefox-ie-edge-safari-opera-rus001-testing-failed
> fix datacite for on ie-11

- app/assets/stylesheets/ubiquity.scss
Small CSS change, Follow up on #185
> Adjust logos position to center of grid-item

- app/assets/stylesheets/ubiquity.scss
- app/views/proprietor/_bl_partners_about.html.erb
- app/views/proprietor/_bl_partners_home.html.erb
Follow up on #185 
IE11 does not support CSS Grid.
> Add CSS for IE11 browser support

- app/helpers/multiple_metadata_fields_helper.rb
- app/views/hyrax/base/_items.html.erb
- app/views/hyrax/homepage/_explore_collections.html.erb
- app/views/hyrax/homepage/_recent_document.html.erb
- app/views/shared/ubiquity/file_sets/_restricted_media.html.erb
- app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
- app/views/shared/ubiquity/works/_items.html.erb
- app/views/shared/ubiquity/works/_member.html.erb
https://trello.com/c/roeWtRL6/394-hide-files-when-under-embargo-lease
> hide files under embargo/lease for public works

- app/forms/hyrax/dataset_form.rb
- app/forms/ubiquity/all_forms_shared_behaviour.rb
Resolves: https://trello.com/c/8ovvZZeH/358-make-publisher-non-compulsory-field
> add publisher as non compulsory field

- docker/docker-compose.no-load-balance-dev.yml
run hyku rails with no load balancer using just port 3000 on Antonio's machine
> run hyku rails with no load balancer using just port 3000

- app/forms/hyrax/dataset_form.rb
- app/forms/ubiquity/all_forms_shared_behaviour.rb
- app/views/shared/ubiquity/_date_published.html.erb
Resolved: https://trello.com/c/DJh3YItV/408-make-date-of-publication-non-compulsory
> change date of publication to a  non compulsory field

- config/authorities/institution.yml
Resolved: https://trello.com/c/4BoThxOJ/357-in-institution-dropdown-change-tate-to-tate
> Update Tate in the drop down authorities menu

- config/authorities/funder.yml
Resolved: https://trello.com/c/gVItVZVf/356-add-new-funders-to-picklist
> Add additional funders to picklist

- config/authorities/institution.yml
Resolved: https://trello.com/c/4BoThxOJ/357-in-institution-dropdown-change-tate-to-tate
> Update institution field for Tate in public view

- config/authorities/rights_statements.yml
Resolved: https://trello.com/c/G3L5ze8j/388-update-rights-statements-authority-list-display
> Update rights statments

- app/helpers/multiple_metadata_fields_helper.rb
- app/views/hyrax/dashboard/collections/_list_works.html.erb
- app/views/hyrax/dashboard/works/_list_works.html.erb
- app/views/hyrax/homepage/_explore_collections.html.erb
- app/views/hyrax/homepage/_featured_fields.html.erb
- app/views/hyrax/homepage/_recent_document.html.erb
- app/views/hyrax/my/works/_list_works.html.erb
- app/views/shared/ubiquity/_thumbnail.html.erb
- app/views/shared/ubiquity/collections/_show_document_list_row.html.erb
- app/views/shared/ubiquity/file_sets/_restricted_media.html.erb
- app/views/shared/ubiquity/works/_member.html.erb
- config/settings.yml
replace bad pdf thumbnails with fontawesome  icons. Switch active_job adapter from async to sidekiq
> replace bad pdf thumbnails with fontawesome icons. Switch active_job adapter from async to sidekiq

- app/views/hyrax/homepage/_explore_collections.html.erb
- app/views/hyrax/homepage/_featured_fields.html.erb
> fix homepage featured

- config/authorities/licenses.yml
Resolved: https://trello.com/c/TV46jd2H/414-add-new-license-breaking-a-work-on-bloarbluk
> add additional licence and set field active to false

- app/views/shared/ubiquity/related_exhibition_date/_related_exhibition_date.html.erb
Restore to using rails select date helpers
> Restore to using rails select date helpers

- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
- app/views/hyrax/dashboard/works/_list_works.html.erb
- app/views/hyrax/homepage/_explore_collections.html.erb
- app/views/hyrax/my/works/_list_works.html.erb
- app/views/shared/ubiquity/_thumbnail_icons.html.erb
- app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
- app/views/shared/ubiquity/collections/_show_document_list_row.html.erb
- app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
Add method to return a file_set_presenter using thumbnail_id in the views and use the returned presenter to fetch file name  etc
> Add method to return a file_set_presenter using thumbnail_id in the views and use the returned presenter to fetch file name  etc

- app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
fix to access thumbnail label solr document for file_set
> fix to access thumbnail label solr document for file_set

- app/helpers/multiple_metadata_fields_helper.rb
- app/views/records/edit_fields/_contributor.html.erb
- app/views/records/edit_fields/_creator.html.erb
- app/views/records/edit_fields/_editor.html.erb
- app/views/shared/ubiquity/alternate_identifier/_show.html.erb
- app/views/shared/ubiquity/contributor/_show.html.erb
- app/views/shared/ubiquity/creator/_show.html.erb
- app/views/shared/ubiquity/editor/_show.html.erb
- app/views/shared/ubiquity/related_identifier/_show.html.erb
re-use additional query when parsing json fields to avoid failure when disk has storage issues
> re-use additional query when parsing json fields to avoid failure when disk has storage issues

- app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
remove code added for debugging from search page
> remove code added for debugging from search page

- app/views/proprietor/_bl_partners_about.html.erb
- app/views/proprietor/_bl_partners_home.html.erb
Add a minor change of position to some of the logos
> Add a minor change of position to some of the logos

- config/authorities/licenses.yml
Resolved: https://trello.com/c/JXeul252/371-01-support-all-the-different-versions-of-the-licences-on-deposit
> Update Hyku authorities list of licences with all different version

- app/helpers/multiple_metadata_fields_helper.rb
Fix PR: https://github.com/ubiquitypress/hyku/pull/233
> Fixed previous pr checking if creator is present

- app/views/shared/ubiquity/_datacite_doi.html.erb
Resolved: https://trello.com/c/69J4bTyw/422-01-review-and-update-the-dois-which-are-listed-in-the-help-text-for-datacite-auto-population
> Change help text for DOI's data autopopulation

- app/views/hyrax/homepage/_home_content.html.erb
- app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
tweaked css to align icons and thumbnail image text
> tweaked css to align icons and thumbnail image text

- app/helpers/application_helper.rb
- app/helpers/ubiquity/google_tag_manager_helper.rb
- app/views/layouts/google/_gtm.html.erb
- app/views/layouts/google/_gtm_body.html.erb
- app/views/layouts/hyrax.html.erb
- config/application.rb
Resolved: https://trello.com/c/RiRF1NUU/426-3-support-google-tag-manager-js-embedding
> enable google tag manager

- config/authorities/licenses.yml
Resolved: https://trello.com/c/NGGsDWIk/439-new-license-id
> Remove duplicate licence

- app/helpers/ubiquity/google_tag_manager_helper.rb
made private methods in the GTM helper:
- def ubiquity_url_parser(host)
- def get_tenant_name_from_url(host)
> made private methods in the GTM helper

- Gemfile.lock
- app/helpers/application_helper.rb
- app/helpers/multiple_metadata_fields_helper.rb
- app/helpers/ubiquity/file_display_helpers.rb
- app/views/hyrax/file_sets/show.html.erb
- app/views/shared/ubiquity/file_sets/_actions.html.erb
- app/views/shared/ubiquity/file_sets/_media_display.html.erb
- app/views/shared/ubiquity/file_sets/_show.html.erb
- app/views/shared/ubiquity/works/_items.html.erb
- app/views/shared/ubiquity/works/_member.html.erb
Add filesize and the use of contact from to request for download of files bigger than 10gb
> Add filesize and the use of contact from to request for download of files bigger than 10gb

- app/views/_logo.html.erb
Resolved: https://trello.com/c/WTbtnEnp/416-update-title-on-shared-layer-from-hyku-to-shared-research-repository
> Change application title conditionally for bl domain

- app/views/splash/_bl_shared_layer.html.erb
- app/views/splash/_new_index.html.erb
- app/views/splash/shared_layer.html.erb
Resolved: https://trello.com/c/kV3Fr2s2/441-1-make-homepage-suitable-for-other-tenants
> content of home page to change according to the tenant

- app/helpers/ubiquity/file_display_helpers.rb
> display files in kilobyes too

- config/authorities/licenses.yml
Resolved :https://trello.com/c/JXeul252/371-01-support-all-the-different-versions-of-the-licences-on-deposit
> set one of the licence to false

- app/services/ubiquity/json_importer.rb
- app/services/ubiquity/queue_import.rb
handle json import when not importing multiple files and when importing multiple files
> handle json import when not importing multiple files and when importing multiple files

- config/authorities/licenses.yml
Resoled : https://trello.com/c/JXeul252/371-01-support-all-the-different-versions-of-the-licences-on-deposit
> remove duplication

- app/helpers/ubiquity/file_display_helpers.rb
- app/views/shared/ubiquity/_thumbnail_icons.html.erb
- app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
- app/views/shared/ubiquity/search_display/_search_thumbnail.html.erb
Resolved some of the issues with thumbnail icons : https://trello.com/c/wBa3vjeS/431-01-default-icon-for-doc-docx-where-thumbnail-has-not-been-generated
> Thumbnail alignment

- config/authorities/licenses.yml
Fixed: https://trello.com/c/JXeul252/371-01-support-all-the-different-versions-of-the-licences-on-deposit-needs-amending
> update licences term

- app/helpers/ubiquity/file_display_helpers.rb
https://trello.com/c/bMI5X4y9/466-fix-file-size-errors-when-no-file
> fix file size errors when file is unavailable

- app/services/concerns/ubiquity/fileset_derivatives_service_override.rb
- config/application.rb
https://trello.com/c/wAtZjhEe/423-solve-problem-with-thumbnail-generation-not-working-for-some-pdfs
> remove layer from thumbnail generation for docx

- config/application.rb
- config/routes.rb
new sidekiq standalone auth:
https://trello.com/c/IG1D3zUr/437-add-standalone-with-basic-auth-for-sidekiq
> sidekiq now uses standalone authentication

- app/views/layouts/hyrax.html.erb
Added a google no index tag to prevent indexing
> add google no-index tag

- .gitignore
- app/controllers/ubiquity/shared_search_controller.rb
- app/forms/ubiquity/all_forms_shared_behaviour.rb
- app/helpers/application_helper.rb
- app/helpers/ubiquity/shared_search_helper.rb
- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/services/ubiquity/shared_search.rb
- app/views/records/edit_fields/_account_cname.html.erb
- app/views/splash/shared_layer.html.erb
- app/views/ubiquity/shared_search/_shared_search_form.html.erb
- app/views/ubiquity/shared_search/index.html.erb
- config/routes.rb
- config/settings.yml
- lib/tasks/add_tenant_cname_to_work.rake
> cross repository shared search

- app/helpers/ubiquity/file_display_helpers.rb
- app/views/hyrax/contact_form/new.html.erb
- app/views/shared/ubiquity/contact/_new.html.erb
- config/locales/hyrax.en.yml
Resolved: https://trello.com/c/nfJ7gTzn/480-add-missing-google-tag-manager-ids-to-tenants
> Contact form

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/application_controller.rb
- app/models/ability.rb
- app/views/_masthead.html.erb
- config/initializers/peek.rb
- config/routes.rb
Removing peek-bar feature from application
> remove peek-bar

- app/assets/stylesheets/ubiquity.scss
Resolved: https://trello.com/c/KyF0anvY/494-individual-repo-search-results-2-changes
> Individual repo search

- app/views/splash/shared_layer.html.erb
- app/views/ubiquity/shared_search/_search_page_top.html.erb
- app/views/ubiquity/shared_search/_shared_search_form.html.erb
- config/locales/en.yml
Resolved: https://trello.com/c/FbAlyRb9/485-shared-search-updates-to-search-box-and-homepage-text-change
> Shared search

- app/helpers/ubiquity/google_tag_manager_helper.rb
quick fix to remove a log statement 
No trello card related to this issue
> remove log statement

- app/views/catalog/_search_form.html.erb
- app/views/shared/ubiquity/catalog/_search_form.html.erb
Resolved: https://trello.com/c/QIywz8RR/488-individual-search-repo-interface-drop-all-for-non-logged-in-users
> Remove dropdown menu -all- when user not logged in

- app/controllers/ubiquity/shared_search_controller.rb
- app/helpers/ubiquity/shared_search_helper.rb
- app/services/ubiquity/shared_search.rb
- app/views/ubiquity/shared_search/_search_page_top.html.erb
- app/views/ubiquity/shared_search/index.html.erb
https://trello.com/c/Szeab9Jt/500-shared-search-results-inconsistent
> Fix Shared search inconsistent results

- app/services/ubiquity/shared_search.rb
https://trello.com/c/EDIWJh7i/501-ensure-resourcetype-search-works-and-added-more-fields-as-searchable
> ensure resource_type is searchable and added more metadata to searchable list

- app/views/hyrax/collections/_show_descriptions.html.erb
- app/views/hyrax/dashboard/collections/_show_descriptions.html.erb
- app/views/shared/ubiquity/collections/_show_descriptions.html.erb
Resolved: https://trello.com/c/YLI7HZRp/490-comment-out-size-from-metadata-for-collection-on-show-collection-and-collection-dashboard-pages
> remove size of work from collection list

- app/controllers/ubiquity/shared_search_controller.rb
- app/views/ubiquity/shared_search/_search_page_top.html.erb
- app/views/ubiquity/shared_search/_search_state.html.erb
https://trello.com/c/DycHHSHy/484-05-2-shared-search-add-grey-box-at-top-to-indicate-what-has-been-searched-for-1-other-change
> grey box at top to indicate what has been searched-for

- app/helpers/ubiquity/file_display_helpers.rb
- app/views/hyrax/homepage/_featured_fields.html.erb
- app/views/shared/ubiquity/_thumbnail_featured.html.erb
Resolved : https://trello.com/c/FFt2oP6Y/499-05-2-changes-to-featured-works-on-individual-repo-homepage
> Featured fields

- app/services/ubiquity/json_importer.rb
https://trello.com/c/eNyJvCYN/510-fix-bug-where-visibility-in-csv-is-not-controlling-visibility-in-hyku
> json importer should create work with visibility as open

- app/services/ubiquity/shared_search.rb
- app/views/ubiquity/shared_search/_search_page_top.html.erb
https://trello.com/c/zkDs2Jck/511-fix-inconsistent-query-result-from-different-machines
> added rows parameter to solr query to ensure consistent results across machines 

- .gitignore
- app/helpers/ubiquity/file_display_helpers.rb
- app/helpers/ubiquity/shared_search_helper.rb
- app/views/ubiquity/shared_search/_shared_search_thumbnail.html.erb
fixed: https://trello.com/c/WDdFLGzW/508-1-shared-search-default-thumbnails-for-known-types-pdf-docx-compressed-archive-should-show-in-place-of-current-unknown-document
> add thumbnail to shared search

- app/assets/stylesheets/ubiquity.scss
- app/views/hyrax/homepage/_featured_fields.html.erb
Resolved : https://trello.com/c/KyF0anvY/494-100-beta2-58-5-individual-repo-search-results-2-changes
This pull request also fixes the font size for metadata only work on featured column(home page)
> Font sizes

- app/helpers/application_helper.rb
- app/helpers/ubiquity/google_tag_manager_helper.rb
- app/views/_logo.html.erb
- app/views/splash/shared_layer.html.erb
Attempt to fix issue with colour when having 2 tenants with different primary colours selected.
Resolves: https://trello.com/c/JPCrTnLq/503-05-shared-search-make-search-button-colour-consistent
> refactor if statement when rendering the bl customized page

- app/services/ubiquity/regenerate_thumbnail.rb
- lib/tasks/regenerate_thumbnails.rake
https://trello.com/c/m63Hxnr3/366-05-run-thumbnail-generator-on-all-works-in-live-repos-that-were-batch-loaded
> Regenerate thumbnails for a specific work using the id or for all works with thesame class name or for all records

- app/services/ubiquity/regenerate_thumbnail.rb
This is an update to the pull request link pasted here, so the Trello card it refers to and how to run it is explained here: https://github.com/ubiquitypress/hyku/pull/317
> updated thumbnail generator

- app/forms/hyrax/form_terms.rb
- app/forms/ubiquity/all_forms_shared_behaviour.rb
- app/helpers/application_helper.rb
- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/views/hyrax/base/_form_progress.html.erb
- app/views/shared/ubiquity/doi/_doi_options.html.erb
- config/application.rb
Resolves: https://trello.com/c/b5EQunaz/514-datacite-doi-minting-user-chooses-doi-minting-options-no-doi-default-draft-doi-mint-registred-mint-findable
> Radio button

- app/helpers/application_helper.rb
- config/application.rb
fix to resolve :https://trello.com/c/b5EQunaz/514-datacite-doi-minting-user-chooses-doi-minting-options-no-doi-default-draft-doi-mint-registred-mint-findable
> Fix to env variable json parser helper

- app/helpers/application_helper.rb
- config/application.rb
updates the earlier fix here:
https://github.com/ubiquitypress/hyku/pull/321
see this card for environment variable to create
https://trello.com/c/b5EQunaz/514-datacite-doi-minting-user-chooses-doi-minting-options-no-doi-default-draft-doi-mint-registred-mint-findable
> should load if tenant does not return json from  environment variable

- app/helpers/application_helper.rb
- app/helpers/ubiquity/google_tag_manager_helper.rb
- app/views/hyrax/base/_form_progress.html.erb
- config/application.rb
load and run hyku with or without tenant_settings json
> load and run hyku with or without tenant_settings json

- app/helpers/application_helper.rb
- app/helpers/ubiquity/google_tag_manager_helper.rb
- config/application.rb
see the trello card below for the environment variable to set
https://trello.com/c/b5EQunaz/514-datacite-doi-minting-user-chooses-doi-minting-options-no-doi-default-draft-doi-mint-registred-mint-findable
> cleanup application.rb and ensure tenant_settings environemnt variable works

- app/jobs/ubiquity_post_to_indexer.rb
- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/models/concerns/ubiquity/work_doi_lifecycle.rb
- app/services/ubiquity/indexer_client.rb
https://trello.com/c/6zxctrsn/528-datacite-doi-minting-hyku-sends-message-rest-post-to-indexer-api-to-confirm-that-a-doi-needs-to-be-minted-updated
> post to indxer

- app/helpers/ubiquity/file_display_helpers.rb
Fixes
- File size issue for multiple file upload
- Increased the file download limit to 20 GB from S3
The file download link has been extended to 20 GB and also fixed the file size issue while listing the files for a specific work.
> Fixed the file size issue in File list and extended the File size download limit

- app/jobs/ubiquity_post_to_indexer.rb
- app/models/concerns/ubiquity/track_doi_options.rb
- app/models/concerns/ubiquity/work_doi_lifecycle.rb
- app/models/external_service.rb
- app/services/ubiquity/doi_service.rb
- app/services/ubiquity/indexer_client.rb
- app/views/hyrax/base/_form_progress.html.erb
- app/views/records/edit_fields/_draft_doi.html.erb
- app/views/shared/ubiquity/_datacite_suffix_generator.html.erb
- db/migrate/20190416105624_create_external_services.rb
- db/migrate/20190418121441_add_file_status_to_uploaded_files.rb
- db/schema.rb
Resolved: https://trello.com/c/D1BIMe49/515-datacite-doi-minting-doi-suffix-is-auto-generated-and-appended-to-prefix-saved-in-a-new-draft-doi-field-that-is-not-displayed-pu
> refactored generation of draft doi

- db/migrate/20190418121441_add_file_status_to_uploaded_files.rb
Fixes unique index error for file status
> removed unique index for file status

- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
no card just removed a random comment used for logging
> remove random comment

- app/models/concerns/ubiquity/track_doi_options.rb
https://trello.com/c/1iyNMzoC/537-stop-duplicate-record-creation-when-the-button-to-generate-draftdoi-is-not-clicked
> stop duplicate record when creating draft_doi in situations where button is not clicked

- app/views/hyrax/base/_form_progress.html.erb
Fixes issue with drop downs for the visibility options
> doi options render below visibility options to allow dropdown list

- app/jobs/add_work_id_to_external_service_job.rb
- app/models/concerns/ubiquity/track_doi_options.rb
- app/models/concerns/ubiquity/work_doi_lifecycle.rb
- app/services/ubiquity/importer_client.rb
- app/services/ubiquity/indexer_client.rb
Fixed Added Condition in loading ENV setting in the datacite module
> Added condition in loading the ENV settings for datacite

- app/jobs/add_work_id_to_external_service_job.rb
- app/services/ubiquity/indexer_client.rb
- config/locales/en.yml
Resolves: https://trello.com/c/ntbUYiki/521-datacite-doi-minting-doi-field-in-hyku-is-populated-with-doi-at-point-of-sending-to-datacite
> update splash page content and official url filed doi auto fill

- db/migrate/20190430130449_change_column_types_in_external_service.rb
Fixed the migration issue in the external service model
> Fixed the migration in the external service

- app/models/concerns/ubiquity/track_doi_options.rb
- app/models/concerns/ubiquity/work_doi_lifecycle.rb
- app/services/ubiquity/indexer_client.rb
fix error to stop post-indexer job to be called twice
> fix error to stop post-indexer job to be called twice

- app/helpers/ubiquity/file_display_helpers.rb
Added nil check in the file_display_helper for tenant link
> Added nil check condition for the tenant

- app/controllers/concerns/ubiquity/uploads_controller_override.rb
- app/controllers/ubiquity/fail_uploads_controller.rb
- app/models/concerns/ubiquity/file_upload_callback.rb
Reverted the FileUpload Enum in the upload module
> Reverted the file_status column with boolean value

- app/helpers/ubiquity/file_display_helpers.rb
Fixed : Loading FileSet records while downloading the file in the localhost.
> S3 url fallback code condition

- app/assets/javascripts/application.js
- app/assets/javascripts/hyku/groups/uploader.js
- app/assets/javascripts/ubiquity/external_services_modal.js
- app/assets/stylesheets/ubiquity.scss
- app/views/hyrax/base/_form_progress.html.erb
- app/views/ubiquity/external_services/_datacite_modal.html.erb
- app/views/ubiquity/external_services/_doi_options.html.erb
Resolved: https://trello.com/c/TumoW8ua/519-datacite-doi-minting-when-user-saves-a-work-that-will-send-a-record-to-datacite-then-it-should-run-validation-and-give-them-a-ch
> Publication year modal

- config/locales/article.en.yml
- config/locales/book_contribution.en.yml
- config/locales/conference_item.en.yml
- config/locales/dataset.en.yml
- config/locales/report.en.yml
Resolved: https://trello.com/c/2raFsSEv/473-amend-doi-field-help-text-and-manipulate-deposited-doi-formats
> Change to doi help text in the deposit form

- config/locales/article.en.yml
- config/locales/book_contribution.en.yml
- config/locales/conference_item.en.yml
- config/locales/dataset.en.yml
- config/locales/report.en.yml
Resolves :https://trello.com/c/2raFsSEv/473-amend-doi-field-help-text-and-manipulate-deposited-doi-formats
> Update doi help text

- app/controllers/hyrax/articles_controller.rb
- app/controllers/hyrax/book_contributions_controller.rb
- app/controllers/hyrax/books_controller.rb
- app/controllers/hyrax/conference_items_controller.rb
- app/controllers/hyrax/datasets_controller.rb
- app/controllers/hyrax/generic_works_controller.rb
- app/controllers/hyrax/images_controller.rb
- app/controllers/hyrax/reports_controller.rb
- app/helpers/ubiquity/file_display_helpers.rb
- app/views/shared/ubiquity/_thumbnail_featured.html.erb
- app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
- app/views/shared/ubiquity/file_sets/_restricted_media.html.erb
- config/application.rb
Resolves: https://trello.com/c/WYuJ4Hu6/151-implement-universal-viewer-for-images-testing-failed
> Universal viewer

- app/assets/javascripts/ubiquity/external_services_modal.js
- app/views/hyrax/base/_form_progress.html.erb
- app/views/hyrax/base/edit.html.erb
- app/views/hyrax/base/new.html.erb
- app/views/ubiquity/external_services/_datacite_modal.html.erb
Resolves: https://trello.com/c/zVADjX5U/544-datacite-doi-minting-warning-pop-up-shows-behind-drop-down-forms
> Modal issue datacite

- app/assets/stylesheets/ubiquity.scss
Resolves: https://trello.com/c/zmH2L6A0/550-change-background-colour-for-announcements
> change announcement background color

- app/services/ubiquity/indexer_client.rb
Resolves: https://trello.com/c/UIXqI00W/551-hyku-repeatedly-posts-to-the-indexer
> Repetead retries

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
- app/helpers/ubiquity/facet_helper_behavior_override.rb
- app/views/_controls.html.erb
- app/views/catalog/_index_list_default.html.erb
- app/views/catalog/index.html.erb
Resolved: https://trello.com/c/EDIWJh7i/501-100-beta2-58-7-individual-shared-search-ensure-resourcetype-search-works-and-added-more-fields-as-searchable-failed
> new-shared-search frontend display tweaks

- app/helpers/ubiquity/external_services_helper.rb
- app/views/hyrax/base/_form_progress.html.erb
Resolves: https://trello.com/c/jjzPMG79/557-datacite-workflow-issue-change-to-display-logic-for-draft-doi-in-deposit-form
> Fix draft-doi display flow

- app/assets/javascripts/ubiquity/external_services_modal.js
- app/helpers/application_helper.rb
- app/helpers/ubiquity/work_show_actions_helper.rb
- app/views/hyrax/base/_show_actions.html.erb
- app/views/records/edit_fields/_official_link.html.erb
- app/views/shared/ubiquity/works/_show_actions.html.erb
Resolves: https://trello.com/c/K4COiYZ7/565-change-to-pop-up-message-when-work-is-embargoed-and-when-a-user-wants-to-delete-a-work-with-a-registered-doi
> Validation message

- app/services/ubiquity/expiry_service.rb
https://trello.com/c/5T3R7wRV/568-fix-embargo-as-it-no-longer-auto-expire
> Fix embargo not expiring

- app/models/concerns/ubiquity/update_shared_index.rb
- app/services/ubiquity/shared_index_solr_service_wrapper.rb
- app/views/shared/ubiquity/catalog/_index_list_default.html.erb
reindex a  work in shared-search if a file is added or if the collection is updated or deleted 
https://trello.com/c/X4BlQc1v/562-reindex-a-work-that-is-already-in-shared-search-in-certain-scenarios
> reindex a  work in shared-search if a file is added or if the collection is updated or deleted "

- app/services/ubiquity/expiry_service.rb
Fixes:
https://trello.com/c/5T3R7wRV/568-15916fix-embargo-as-it-no-longer-auto-expires
- Changed the query to pluck the cname and the records
> changed the query to pluck the cname

- app/assets/javascripts/ubiquity/title_check.js
- app/controllers/available_ubiquity_titles_controller.rb
- app/controllers/catalog_controller.rb
- app/forms/hyrax/article_form.rb
- app/forms/hyrax/book_contribution_form.rb
- app/forms/hyrax/book_form.rb
- app/forms/hyrax/conference_item_form.rb
- app/forms/hyrax/dataset_form.rb
- app/forms/hyrax/generic_work_form.rb
- app/forms/hyrax/image_form.rb
- app/forms/hyrax/report_form.rb
- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/models/solr_document.rb
- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
- app/services/ubiquity/title_checker.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- app/views/records/edit_fields/_alt_title.html.erb
- app/views/records/edit_fields/_alternative_title.html.erb
- config/locales/article.en.yml
Resolved: https://trello.com/c/s3TeIMi5/569-update-alternative-title-to-follow-samvera-hyrax-way
> refactor alternative title to follow Hyrax samvera pattern

- app/models/solr_document.rb
Fixes : Issue in displaying the Alternative Journal Title value in the display form
> Fixed the issue in the Alternative Journal Title display form

- app/assets/javascripts/ubiquity/datacite.js
- app/services/ubiquity/crossref_response.rb
- app/views/records/edit_fields/_issue.html.erb
- app/views/records/edit_fields/_pagination.html.erb
Fixes: https://trello.com/c/402qwrSn/413-1599-pull-metadata-from-crossref-when-provided-with-a-doi-more-dev-needed
- Added Volume, Pagination, Issue and corrected the fetching of eissn
> Added volumne and issue fields for the cross ref url

- app/models/concerns/ubiquity/all_models_virtual_fields.rb
Fixes https://trello.com/c/KD8PBgok/571-when-manipulating-the-isni-field-and-orcid-on-save-pay-attention-to-backslash-and-tabs
- Squish method calling of the value is string
> Fixed squishing for the url class values

- app/assets/javascripts/ubiquity/datatable-settings.js
- app/assets/stylesheets/ubiquity.scss
- app/views/shared/ubiquity/collections/_show_document_list.html.erb
- app/views/shared/ubiquity/collections/_show_document_list_row.html.erb
Fixes: https://trello.com/c/jwbjps82/575-3-cleanups-polishings-to-collection-page
- Line up the heading of each column in the collection table
- Remove sharing icon from the attachment thumbnail
- Apply order column highlighting
> Collection view new changes

- app/models/concerns/ubiquity/all_models_virtual_fields.rb
- app/models/file_set.rb
- app/services/ubiquity/expiry_service.rb
Fixes 
- Error thrown on saving the work expiry service
> Removed the status column reference from the new model

- app/jobs/ubiquity_work_expiry_job.rb
- app/models/file_set.rb
- lib/tasks/create_expiry_service_records.rake
Fixes: https://trello.com/c/5T3R7wRV/568-15922fix-embargo-as-it-no-longer-auto-expires
Fixed the reference to the embargo and lease_expiration date
> Added referencing the embargo_Release_date and lease_expiration_date

- app/helpers/multiple_metadata_fields_helper.rb
- app/helpers/ubiquity/collection_list_helper.rb
- app/services/ubiquity/parse_json.rb
- app/views/shared/ubiquity/collections/_show_document_list_row.html.erb
Fixes : https://trello.com/c/tzVlOVtb/261-15916-3-update-metadata-shown-on-individual-collections
> Fixed the collection table issue in the UI

- app/jobs/ubiquity_work_expiry_job.rb
- lib/tasks/create_expiry_service_records.rake
Fixes https://trello.com/c/5T3R7wRV/568-15922fix-embargo-as-it-no-longer-auto-expires
Added try in the lease_expiration_date
> Added try in the release date check for embargo and lease

- app/forms/hyrax/generic_work_form.rb
Resolves: https://trello.com/c/gP00tHJD/336-15916-not-working-1-make-alternative-title-and-alternative-journal-title-multiple-fields
> fixed alternative-journal-title

- app/models/concerns/ubiquity/csv_export_util.rb
- app/services/ubiquity/csv_data.rb
- app/services/ubiquity/csv_data_remap.rb
- app/services/ubiquity/csv_generator.rb
- app/views/admin/exports/index.html.erb
https://trello.com/c/8QuJT627/411-make-improvements-to-export-a-file-of-the-repository-metadata
https://trello.com/c/bX8OZDCo/579-add-new-work-types-to-csv-export-by-work-type
> Export records to CSV after remapping the keys and then reordering based on the order given by Bl

- app/services/ubiquity/json_importer.rb
- app/services/ubiquity/queue_import.rb
https://trello.com/c/ny0pVK4C/584-allow-json-importer-to-update-records-based-on-keys-in-imported-csv
> allow json importer to update records based on keys in imported csv

- app/views/shared/ubiquity/contact/_new.html.erb
Fixes : https://trello.com/c/28EMeLhn/583-update-save-to-send-when-contact-form-is-completed-and-sent
> Changed the typo in submitting the contact form

- app/helpers/multiple_metadata_fields_helper.rb
- app/models/concerns/ubiquity/all_models_virtual_fields.rb
- app/services/ubiquity/crossref_response.rb
Fixes 
- https://trello.com/c/402qwrSn/413-15922-pull-metadata-from-crossref-when-provided-with-a-doi-more-dev-needed
- https://trello.com/c/KD8PBgok/571-15922-when-manipulating-the-isni-field-and-orcid-on-save-pay-attention-to-backslash-and-tabs
> Cross ref issn type update

- app/controllers/ubiquity/account_settings_controller.rb
- app/models/concerns/ubiquity/account_self_join_association.rb
- app/views/hyrax/admin/stats/_email_reports.html.erb
- app/views/hyrax/admin/stats/show.html.erb
- app/views/ubiquity/account_settings/edit.html.erb
- app/views/ubiquity/account_settings/index.html.erb
Resolves: https://trello.com/c/6pVoZIDH/145-10-receive-and-set-up-scheduled-reports-eg-monthly-annual-relating-to-content-and-usage-of-my-repository
> ResolvedTab reports section

- app/helpers/multiple_metadata_fields_helper.rb
Fixes https://trello.com/c/KD8PBgok/571-v15925-15922-not-working-when-manipulating-the-isni-field-and-orcid-on-save-pay-attention-to-backslash-and-tabs
> Added the support for the url in the orcid and the isni value

- app/models/concerns/ubiquity/multiple_modules.rb
Fixed if condition to address comment in the card: https://trello.com/c/fTpzGNZV/450-v15924update-filters-to-include-filter-by-full-text-availability
> changed the if condition to adjust to the revisited business rule

- app/services/ubiquity/indexer_client.rb
Resolves: https://trello.com/c/jVNcXHty/596-datacite-send-service-code-as-part-of-the-post-to-indexer
> Add service_code to indexer posting

- app/views/records/edit_fields/_resource_type.html.erb
- config/authorities/resource_types.yml
Fixes : https://trello.com/c/7qX57yb8/598-add-default-work-type-as-audio-when-depositing-work-type-time-based-media
> Add work type time based media

- app/views/hyrax/homepage/_featured.html.erb
Fixeshttps://trello.com/c/0wohofBr/581-featured-items-on-homepage-needs-to-consider-visibility-of-work-and-status-of-users-viewing-page
> Featured work list issue

- app/models/concerns/ubiquity/multiple_modules.rb
Fixes:  https://trello.com/c/fTpzGNZV/450-v15924not-working-update-filters-to-include-filter-by-full-text-availability
> reviewd logic to create fileavailability facet

- app/controllers/catalog_controller.rb
- app/models/article.rb
- app/models/book.rb
- app/models/book_contribution.rb
- app/models/concerns/ubiquity/multiple_modules.rb
- app/models/conference_item.rb
- app/models/dataset.rb
- app/models/exhibition_item.rb
- app/models/generic_work.rb
- app/models/image.rb
- app/models/report.rb
- app/models/thesis_or_dissertation.rb
- app/models/time_based_media.rb
Switched off the file availability facet
> file-availability filter switched off

- config/authorities/resource_types.yml
Minor fix to allow the resources type to be loaded in time based media work type
> fixed a typo

- app/models/concerns/ubiquity/csv_export_util.rb
- app/services/ubiquity/csv_data.rb
- app/services/ubiquity/csv_data_remap.rb
- app/services/ubiquity/csv_generator.rb
https://trello.com/c/8QuJT627/411-v15924-make-improvements-to-export-a-csv-file-of-the-repository-metadata-revert-before-release-to-live
> reverted changes to csv download, so the exported csv headers are no longer in same order as imported csv headers

- app/jobs/ubiquity_post_to_indexer_job.rb
- app/models/concerns/ubiquity/work_doi_lifecycle.rb
- app/services/ubiquity/indexer_client.rb
Fixes: the issue with official link not being generated on sandbox
> Official url bug

- app/helpers/ubiquity/file_display_helpers.rb
Fixes: https://trello.com/c/K0xQTztX/599-create-feature-switch-environment-variable-to-switch-off-s3-download-link
> Added the ENV variable for the s3 download switch specific to live url

- app/models/concerns/ubiquity/all_models_virtual_fields.rb
Fixed : https://trello.com/c/KD8PBgok/571-v15926-v15925-15922-not-working-when-manipulating-the-isni-field-and-orcid-on-save-pay-attention-to-backslash-and-tabs-still-not
> Added code to modify the orcid and isni values

- app/models/concerns/ubiquity/track_doi_options.rb
Resolves: https://trello.com/c/JBtZ2ceF/603-fixing-the-way-hyku-checks-for-a-manual-valid-doi
> fix for Bad URI

- app/jobs/add_work_id_to_external_service_job.rb
- app/models/concerns/ubiquity/all_models_virtual_fields.rb
- app/models/concerns/ubiquity/track_doi_options.rb
- app/services/ubiquity/indexer_client.rb
- app/views/ubiquity/external_services/_datacite_suffix_generator.html.erb
Fixes: https://trello.com/c/D1BIMe49/515-15827-doi-minting-doi-suffix-is-auto-generated-and-appended-to-prefix-saved-in-a-new-draft-doi-field-that-is-not-displayed-publi
> Reorder javascript to send back the value to draftdoi hidden field, and reorder the callback to fix draft-doi generation when no button is clicked

- app/actors/hyrax/actors/file_set_actor.rb
Fixes: https://trello.com/c/bcQ45rCV/577-v15924-loading-new-version-of-file-needs-to-be-possible-from-edit-file-page-revert-before-release-to-live
> File version issue fix

- app/views/shared/ubiquity/_thumbnail_icons_with_restrictions.html.erb
https://trello.com/c/yJZ6cnSR/604-fix-page-load-issues-on-local-machine
> fix homepage not loading when a file_set is empty for a work

- app/assets/javascripts/hyku/groups/uploader.js
Fixes : https://trello.com/c/yyRJvIHv/606-adding-retry-option-and-increase-the-file-chunk-size-for-the-upload
> Added retry option and the increased the chunk size

- app/models/concerns/ubiquity/update_shared_index.rb
- app/services/ubiquity/shared_index_solr_service_wrapper.rb
> Fix fedora error when running file availability rake task

- lib/tasks/ubiquity_index_file_availability_facet.rake
> when running file availability rake task switch tenant after each loop to see if eliminates a fedora error

- app/indexers/file_set_indexer.rb
- app/models/concerns/ubiquity/update_shared_index.rb
> rescue when to_solr fails in file_set indexer when running  file_availability rake task

- app/controllers/catalog_controller.rb
Temporary Switching off file availability facet to allow for live release
> Temporary Switching off file availability facet

- app/controllers/ubiquity/account_settings_controller.rb
- app/models/concerns/ubiquity/account_self_join_association.rb
- app/models/concerns/ubiquity/update_shared_index.rb
- app/services/ubiquity/shared_index_solr_service_wrapper.rb
- app/views/ubiquity/account_settings/edit.html.erb
- app/views/ubiquity/account_settings/index.html.erb
No trello card. Just code reversion to remove features not going to live
> revert enabling shared search from the ui & remove ability stop app from failing when deleting a work

- app/controllers/concerns/ubiquity/citations_export_concern.rb
Fixes: https://trello.com/c/piOtS2bg/476-v15924-5-enable-reference-management-tools-zotero-endnote-mendeley-to-read-and-export-work-metadata-via-ris-file-download
> Fixed the resource type and the Book title issue in the RID format

- app/controllers/catalog_controller.rb
Re-enabled file availability facet on test
> re-enabled file_availability UI

- app/controllers/concerns/ubiquity/citations_export_concern.rb
- app/helpers/multiple_metadata_fields_helper.rb
- app/services/ubiquity/parse_json.rb
No Card for this PR (part of Code Optimization)
> Removed unwanted code and re-used the exisitng method

- app/services/ubiquity/parse_json.rb
- lib/tasks/ubiquity_resave_records.rake
Fixes: No Card
It fixes the issue in running the rake task on updating the record and fix the records having unfilled family name or given name for Contributor and Creator
> Fixed the issue with the contributor in running the rake task

- app/assets/javascripts/application.js
- app/assets/javascripts/ubiquity/search_page.js
https://trello.com/c/cuDGc87x/582-fix-display-of-all-collections-filter-human-readable-type-sim
> change text from collection to collections in search page when we click view collections on homepage

- config/locales/en.yml
Resolves: https://trello.com/c/LelKAVFi/615-refresh-the-text-at-oarbl
> Update text in the splash page

- config/authorities/institution.yml
- lib/tasks/update_kew_institution_name.rake
Fixes : https://trello.com/c/SHgqjLNV/133-add-a-new-iro-to-join-the-shared-repository-interface
> Updated the institution name of kew and added rake task

- app/models/concerns/ubiquity/csv_export_util.rb
- app/services/ubiquity/csv_data.rb
- app/services/ubiquity/csv_data_remap.rb
- app/services/ubiquity/csv_generator.rb
https://trello.com/c/8QuJT627/411-v15924-make-improvements-to-export-a-csv-file-of-the-repository-metadata-was-reverted-before-release-1600-needs-un-reverting
> ensure the order of keys in in exported csv match the order in imported csv

- app/views/proprietor/_bl_partners_about.html.erb
Fixes: https://trello.com/c/cHyf9Z6U/625-update-about-page-on-shared-layer
> Updated the text in the shared layer

- app/models/concerns/ubiquity/update_shared_index.rb
- app/services/ubiquity/shared_index_solr_service_wrapper.rb
deleting a work with a file should not throw errorhttps://trello.com/c/XhULjrbX/616-deleting-a-work-with-a-file-should-no-longer-crash-the-app-was-reverted-needs-un-reverting
> deleting a work with a file should not throw error

- app/helpers/ubiquity/file_display_helpers.rb
- app/presenters/hyku/file_set_presenter.rb
- app/views/hyrax/file_sets/_form.html.erb
- app/views/hyrax/file_sets/_show_details.html.erb
- app/views/records/edit_fields/_license.html.erb
- app/views/records/edit_fields/_license_file.html.erb
- app/views/shared/ubiquity/file_sets/_form.html.erb
- app/views/shared/ubiquity/file_sets/_show_details.html.erb
- app/views/shared/ubiquity/works/_items.html.erb
- app/views/shared/ubiquity/works/_member.html.erb
- config/authorities/licenses.yml
Fixed: https://trello.com/c/ZZmvOTOA/19-3-submitter-add-licence-information-at-the-level-of-each-individual-file-uploaded-within-the-work-rus016-edited
> File licence options

- app/assets/javascripts/ubiquity/search_page.js
Resolved: https://trello.com/c/cuDGc87x/582-1615fix-display-of-all-collections-filter-human-readable-type-sim
> Removed human readable type from collections filter

- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
- app/indexers/shared_indexer.rb
- app/models/current_scope.rb
- app/models/solr_document.rb
- app/services/ubiquity/doi_service.rb
- app/services/ubiquity/fetch_all_orcid_isni.rb
Fixes: https://trello.com/c/gemPv5Tz/165-1612-10-oai-pmh-harvesting-is-in-place
Added the newly requested fields in OAI-PMH
> Added new values in the oai-pmh template

- app/helpers/ubiquity/importer_link_helper.rb
- app/views/admin/exports/index.html.erb
- app/views/hyrax/dashboard/_sidebar.html.erb
- config/locales/en.yml
Fixed: https://trello.com/c/AyAyx1fl/22-1-approver-import-a-file-of-metadata-eg-csv-xml-into-the-repository-create-multiple-records-add-link-on-dashboard-navigation-an
> add import link to dashboard and from CSV export page

- app/models/concerns/ubiquity/csv_export_util.rb
- app/services/ubiquity/csv_data_remap.rb
- app/services/ubiquity/csv_generator.rb
https://trello.com/c/8QuJT627/411-1615v15924-make-improvements-to-export-a-csv-file-of-the-repository-metadata
> correct csv download order, change file to file_url and remove creator_position, contributor_position and editor_position headers

- app/views/admin/exports/index.html.erb
> Reduced text size to 18px

- app/indexers/shared_indexer.rb
- app/mailers/work_report_mailer.rb
- app/services/ubiquity/fetch_all_orcid_isni.rb
- app/services/ubiquity/fetch_mailer_report_data.rb
- docker/supervisord-worker.conf
Fixes: https://trello.com/c/5pZQyExr/594-10-receive-and-set-up-scheduled-reports-eg-monthly-annual-relating-to-content-and-usage-of-my-repository
Added fix for the mailer report for records which has blank values in sandbox
> Mailer report new changes

- app/controllers/application_controller.rb
- app/controllers/ubiquity/superadmin_sessions_controller.rb
- app/views/_admin_util_links.html.erb
- app/views/shared/_footer.html.erb
- app/views/ubiquity/superadmin_sessions/_superadmin_login_link.html.erb
- app/views/ubiquity/superadmin_sessions/_superadmin_logout_link.html.erb
- app/views/ubiquity/superadmin_sessions/new.html.erb
- config/routes.rb
https://trello.com/c/e0UuNKfE/602-5-solve-bug-with-superuser-admin-login-on-shared-area
> fix inability of super_admin administrator login from root_page or shared search page

- app/views/admin/exports/index.html.erb
Resolved : https://trello.com/c/AyAyx1fl/22-16111-approver-import-a-file-of-metadata-eg-csv-xml-into-the-repository-create-multiple-records-add-link-on-dashboard-navigation
An update in the text was required.
> Changed the help text according to the new specification

- app/helpers/multiple_metadata_fields_helper.rb
- app/models/concerns/ubiquity/all_models_virtual_fields.rb
Fixes: https://trello.com/c/4IdaNaeh/632-stop-stripping-x-from-the-end-of-orcids-on-save
> Added X in the regex to allow the value in generating the url for ORCID

- app/views/shared/ubiquity/file_sets/_actions.html.erb
- app/views/shared/ubiquity/file_sets/_restricted_media.html.erb
Fixes: https://trello.com/c/ANYLsOX4/634-embargoed-files-when-not-logged-in-no-thumbnail-should-be-showing-and-download-should-not-be-possible
> fixed the issue with blu icon for embargoed files and download link

- app/views/shared/ubiquity/contributor/_contributor_js.html.erb
- app/views/shared/ubiquity/contributor/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/contributor/_new_form.html.erb
- app/views/shared/ubiquity/creator/_creator_js.html.erb
- app/views/shared/ubiquity/creator/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/creator/_new_form.html.erb
- app/views/shared/ubiquity/editor/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/editor/_editor_js.html.erb
- app/views/shared/ubiquity/editor/_new_form.html.erb
Fixes: https://trello.com/c/a8TqMKqb/636-correct-the-label-in-the-deposit-form-for-creator-contributor-editor-orcid
Fixed the issue with the label
> Fixed the issue with the label in creator/editor/contributor

- app/models/concerns/ubiquity/shared_metadata.rb
Resolves: https://trello.com/c/HbkCkgTL/628-allow-multiple-duration-fields-to-deposit-form
> allow multiple: true for duration field

- app/models/concerns/ubiquity/track_doi_options.rb
Fixes: https://trello.com/c/PBeRI1Rh/637-rake-task-error-when-re-saving-a-record-will-be-tested-internally-by-up
> Addressed nil error on split when running rake task to resave a work

- app/services/ubiquity/csv_data_remap.rb
- app/services/ubiquity/csv_generator.rb
https://trello.com/c/8QuJT627/411-1615v15924-make-improvements-to-export-a-csv-file-of-the-repository-metadata
> further re-ordering of csv headers during export

- app/services/ubiquity/csv_data_remap.rb
https://trello.com/c/8QuJT627/411-161171615v15924-make-improvements-to-export-a-csv-file-of-the-repository-metadata
> add series_name back to csv_export

- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/ubiquity/oai_extension.rb
- app/models/current_scope.rb
- app/views/work_report_mailer/_table_data.html.erb
- config/application.rb
Fixes https://trello.com/c/gemPv5Tz/165-16117-16116-oai-pmh-harvesting-is-in-place
Fix the url issue in OAI-PMH
> Oai request url fix

- app/services/ubiquity/csv_data_remap.rb
Added the alternative_journal title to the CSV_HEARDERS_ORDER array in csv_data_remap.rb
> add the alternative_journal_title field in the export

- app/controllers/ubiquity/solr_wrapper_extension.rb
- config/application.rb
Fixes https://trello.com/c/RASVfuXe/638-opai-pmh-restrict-works-that-are-not-currently-public-from-the-feed-index
Applying public filter in OAI-PMH
> Added publich filter for the oai

- app/controllers/ubiquity/solr_wrapper_extension.rb
Fixes https://trello.com/c/KW2qEpfS/639-oai-pmh-restrict-works-that-are-in-review-from-the-feed-index
> Fixed the issue with the pending review

- app/controllers/ubiquity/oai_extension.rb
- app/controllers/ubiquity/oai_solr_wrapper_extension.rb
- app/controllers/ubiquity/solr_wrapper_extension.rb
- config/application.rb
Fixes: https://trello.com/c/gemPv5Tz/165-16120-16117-16116-oai-pmh-harvesting-is-in-place
> Fixed the issue with the collection

- app/services/ubiquity/importer_client.rb
Fixes Updated the s3 url api wrapper url configurable
> Added the base url configurable for the s3

- app/indexers/collection_indexer.rb
- app/models/solr_document.rb
- app/services/ubiquity/fetch_tenant_url.rb
Fixes: https://trello.com/c/gemPv5Tz/165-16120-16117-16116-oai-pmh-harvesting-is-in-place
Once deployed to test, please run the below rake task to update the column.
`rake ubiquity_resave_records:update_specific_model[sandbox.repo-test.ubiquity.press,collection]`
> Added soruce url link for the collection

- app/mailers/work_report_mailer.rb
- app/services/ubiquity/fetch_mailer_report_data.rb
This will allow to merge @ashikajith work on mailer refactoring
> Revert "Merge pull request #525 from ubiquitypress/refactor-mailer"

- app/mailers/work_report_mailer.rb
- app/services/ubiquity/doi_service.rb
- app/services/ubiquity/report_mailer.rb
Fixes: Code Refactoring in the Report Mailer class
> Added new indexer for the mailer

- app/helpers/ubiquity/preselect_institution_helper.rb
Resolves: issue with not preselecting institutions form the drop-down list for Kew and bl-demo.
Card to be created in JIRA
> add pre-selected institution field choice for bl-dem and kew-demo

- app/models/concerns/ubiquity/track_doi_options.rb
- app/renderers/ubiquity/external_url_attribute_renderer.rb
Resolves issue with creating a clickable manual doi. 
A JIRA card will be created for this PR
> making a manual doi a clickable link

- app/services/ubiquity/indexer_client.rb
Fixes: A connection error when posting to indexer from local host
> rescue tcp connection error when posting to indexer

- config/database.yml
- db/schema.rb
- docker/docker-compose.dev.yml
- docker/local-docker-compose.yml
No card.  To allow running test from local environment outside docker container
> add static ip to docker-compose files

- app/assets/javascripts/ubiquity/search_page.js
- docker/docker-compose.no-load-balance-dev.yml
fixes issue with clear filters button linking to the wrong page
> fix issue with clear filters linking to the wrong page

- app/assets/javascripts/application.js
- app/assets/javascripts/ubiquity/work_page.js
- app/views/hyrax/base/show.html.erb
Fixes the issue with the approval form dropping down to the footer
> Fix positiong issue with approval form

- config/locales/generic_work.en.yml
- config/locales/thesis_or_dissertation.en.yml
Fix the issue with wrong help text on modal that appears when creating a new work
> amend text on worktype modal on landing page

- app/forms/hyrax/time_based_media_form.rb
Fixes the issue with the field version number not saving for time based media
> fixing version field for time_based_media model

- app/assets/javascripts/ubiquity/external_services_modal.js
This fixes a bug when minting doi. The bug allowed to mint a even without a publishing date.
https://ubiquitypress.atlassian.net/browse/REPO-514
> add a js event change to detect a change of work form private to public

- app/views/shared/ubiquity/file_sets/_show.html.erb
- app/views/shared/ubiquity/file_sets/_show_details.html.erb
Fixes issue with depositor email and activity log showing even when not logged in
> remove depositor email and activity log if not logged in

- app/views/shared/ubiquity/file_sets/_show_details.html.erb
showing depositor email only for logged in user
> showing depositor email only for logged in user

- app/services/ubiquity/json_importer.rb
https://ubiquitypress.atlassian.net/browse/REPO-519
> manually set admin-set to admin_set/default when importing record via the python importer

- app/views/records/edit_fields/_version_number.html.erb
This PR adds a help text to the version number field.
> added a help text for version number field

- app/views/records/edit_fields/_version_number.html.erb
Updating version number help text.
> Update help text for version number

- app/controllers/ubiquity/fail_uploads_controller.rb
- app/helpers/ubiquity/file_display_helpers.rb
- app/jobs/ubiquity_post_file_to_importer_job.rb
- app/models/file_set.rb
- app/services/ubiquity/importer_client.rb
- app/views/api/v1/files/index.json.jbuilder
- config/routes.rb
- spec/jobs/ubiquity_post_file_to_importer_job_spec.rb
This PR updates the repo wrapper api to new end point
> update api end point for repo wrapper

- app/views/api/v1/work/_work.json.jbuilder
this fix adds the type field to the work endpoint
> add type field to work end point

- app/services/ubiquity/load_fedora_to_solr.rb
- app/services/ubiquity/load_fedora_uri_files.rb
- lib/uri_json/missing-repo-index_bl-demo.json
- lib/uri_json/missing-repo-index_bl.json
- lib/uri_json/missing-repo-index_britishmuseum-demo.json
- lib/uri_json/missing-repo-index_kew.json
- lib/uri_json/missing-repo-index_mola.json
- lib/uri_json/missing-repo-index_nms-demo.json
- lib/uri_json/missing-repo-index_nms.json
- lib/uri_json/missing-repo-index_tate-demo.json
- lib/uri_json/missing-repo-index_tate.json
This PR to add missing files from fedora to solr
> Upload files from fedora to solr

- app/views/api/v1/work/_work.json.jbuilder
This PR address the issue with the missing fields from the work endpoint
> Add missing field from work endpoint

- lib/uri_json/missed-indexes-nms.json
Adds additional nms missed records during re-indexing
> add missed nms indexes

- app/services/ubiquity/api_utils.rb
- app/views/api/v1/files/index.json.jbuilder
This PR adds file licences to files endpoint
> add file licences to files endpoint

- app/views/api/v1/files/index.json.jbuilder
add information about embargo and lease dates on file end-point
```
json.embargo_release_date  work['embargo_release_date_dtsi']
json.lease_expiration_date  work['lease_expiration_date_dtsi']
```
> add information about embargo and lease dates on file end-point

- app/views/api/v1/tenant/_tenant.json.jbuilder
This PR adds the google tag manager key per tenant
> adding google tag manager key to tenant end point

- app/controllers/api/v1/search_controller.rb
This PR it is an attempt to exclude works with changes required status from searching
> add a filter to solr filter query in search-controller

- app/controllers/api/v1/highlights_controller.rb
- app/controllers/concerns/ubiquity/api_controller_utility_methods.rb
This PR addresses the issue with ordering the featured work
> Ordering featured work

- app/controllers/api/v1/highlights_controller.rb
Removing the order of featured works that was causing the highlights end-point not to work
> removing the featured works ordering

- app/controllers/api/v1/highlights_controller.rb
attempt to remove the bug introduced when trying to reorder the featured works
> remove the ordering of featured work

- .bumpversion.cfg
- app/controllers/api/v1/highlights_controller.rb
- app/controllers/concerns/ubiquity/api_controller_utility_methods.rb
- config/initializers/version.rb
This PR removes works marked as pending reviews and changes required from recent additions in the highlights end-point
> Visibility fix

- app/views/api/v1/work/_work.json.jbuilder
This PR adds the workflow_status to the work end point
> add workflow_status field in the work json

- app/controllers/api/v1/collection_controller.rb
- app/controllers/api/v1/work_controller.rb
- app/models/concerns/ubiquity/caching_single.rb
- app/services/ubiquity/api_utils.rb
- app/views/api/v1/collection/_collection.json.jbuilder
- app/views/api/v1/collection/_work.json.jbuilder
- app/views/api/v1/work/_work.json.jbuilder
This PR adds more caching to improve performance
> added more caching

- .bumpversion.cfg
- app/controllers/api/v1/collection_controller.rb
- app/controllers/api/v1/highlights_controller.rb
- config/initializers/version.rb
This PR allows restricted collection not to be visible form the highlights end-point
> excluding private collections from highlights endpoint

- config/routes.rb
Fixes: https://ubiquitypress.atlassian.net/secure/RapidBoard.jspa?rapidView=6&modal=detail&selectedIssue=REPO-542&quickFilter=15
> update the routes for citations to serve the new front end

- app/controllers/api/v1/search_controller.rb
Fixes: https://ubiquitypress.atlassian.net/secure/RapidBoard.jspa?rapidView=6&modal=detail&selectedIssue=REPO-544&quickFilter=15
> re-included module for error handling in the search controller

- app/views/_controls.html.erb
- app/views/_logo.html.erb
- app/views/_masthead.html.erb
- app/views/hyrax/homepage/_announcement.html.erb
- app/views/hyrax/homepage/_marketing.html.erb
- app/views/hyrax/homepage/index.html.erb
- app/views/layouts/hyrax.html.erb
- app/views/splash/shared_layer.html.erb
fixes: https://ubiquitypress.atlassian.net/browse/REPO-541
> Shared layer blank

- app/actors/hyrax/actors/presentation_actor.rb
- app/controllers/hyrax/presentations_controller.rb
- app/forms/hyrax/presentation_form.rb
- app/indexers/book_chapter_indexer.rb
- app/indexers/presentation_indexer.rb
- app/models/presentation.rb
- app/presenters/hyrax/presentation_presenter.rb
- app/views/hyrax/presentations/_presentation.html.erb
- config/authorities/resource_types.yml
- config/initializers/hyrax.rb
- config/locales/presentation.de.yml
- config/locales/presentation.en.yml
- config/locales/presentation.es.yml
- config/locales/presentation.fr.yml
- config/locales/presentation.it.yml
- config/locales/presentation.pt-BR.yml
- config/locales/presentation.zh.yml
- spec/actors/hyrax/actors/presentation_actor_spec.rb
- spec/controllers/hyrax/presentations_controller_spec.rb
- spec/features/create_presentation_spec.rb
- spec/forms/hyrax/presentation_form_spec.rb
- spec/models/presentation_spec.rb
- spec/presenters/hyrax/presentation_presenter_spec.rb
This PR adds the presentation work-type and related fields according to specifications
> add presentation worktype and fields

- app/actors/hyrax/actors/text_work_actor.rb
- app/controllers/catalog_controller.rb
- app/controllers/hyrax/text_works_controller.rb
- app/forms/hyrax/text_work_form.rb
- app/indexers/text_work_indexer.rb
- app/models/solr_document.rb
- app/models/text_work.rb
- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
- app/presenters/hyrax/text_work_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- app/views/hyrax/text_works/_text_work.html.erb
- config/authorities/resource_types.yml
- config/initializers/hyrax.rb
- config/locales/text_work.de.yml
- config/locales/text_work.en.yml
- config/locales/text_work.es.yml
- config/locales/text_work.fr.yml
- config/locales/text_work.it.yml
- config/locales/text_work.pt-BR.yml
- config/locales/text_work.zh.yml
- spec/actors/hyrax/actors/text_work_actor_spec.rb
- spec/controllers/hyrax/text_works_controller_spec.rb
- spec/features/create_text_work_spec.rb
- spec/forms/hyrax/text_work_form_spec.rb
- spec/models/text_work_spec.rb
- spec/presenters/hyrax/text_work_presenter_spec.rb
Pr for TextWork type for pacific
> Complete WorkText type

- app/actors/hyrax/actors/news_clipping_actor.rb
- app/controllers/catalog_controller.rb
- app/controllers/hyrax/news_clippings_controller.rb
- app/forms/hyrax/news_clipping_form.rb
- app/indexers/news_clipping_indexer.rb
- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/models/concerns/ubiquity/shared_metadata.rb
- app/models/news_clipping.rb
- app/models/solr_document.rb
- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
- app/presenters/hyrax/news_clipping_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- app/views/hyrax/news_clippings/_news_clipping.html.erb
- app/views/shared/ubiquity/json_fields_partials/_institutional_relationship.html.erb
- config/authorities/resource_types.yml
- config/initializers/hyrax.rb
- config/locales/news_clipping.de.yml
- config/locales/news_clipping.en.yml
- config/locales/news_clipping.es.yml
- config/locales/news_clipping.fr.yml
- config/locales/news_clipping.it.yml
- config/locales/news_clipping.pt-BR.yml
- config/locales/news_clipping.zh.yml
- spec/actors/hyrax/actors/news_clipping_actor_spec.rb
- spec/controllers/hyrax/news_clippings_controller_spec.rb
- spec/features/create_news_clipping_spec.rb
- spec/forms/hyrax/news_clipping_form_spec.rb
- spec/models/news_clipping_spec.rb
- spec/presenters/hyrax/news_clipping_presenter_spec.rb
This Pr add the Pacific data model NewsClipping
> completed NewsClipping work type

- app/actors/hyrax/actors/image_work_actor.rb
- app/controllers/hyrax/image_works_controller.rb
- app/forms/hyrax/image_work_form.rb
- app/indexers/image_work_indexer.rb
- app/models/image_work.rb
- app/presenters/hyrax/image_work_presenter.rb
- app/views/hyrax/image_works/_image_work.html.erb
- config/authorities/resource_types.yml
- config/initializers/hyrax.rb
- config/locales/image_work.de.yml
- config/locales/image_work.en.yml
- config/locales/image_work.es.yml
- config/locales/image_work.fr.yml
- config/locales/image_work.it.yml
- config/locales/image_work.pt-BR.yml
- config/locales/image_work.zh.yml
- spec/actors/hyrax/actors/image_work_actor_spec.rb
- spec/controllers/hyrax/image_works_controller_spec.rb
- spec/features/create_image_work_spec.rb
- spec/forms/hyrax/image_work_form_spec.rb
- spec/models/image_work_spec.rb
- spec/presenters/hyrax/image_work_presenter_spec.rb
This PR adds the ImageWork work-type to pacific
> Complete ImageWork work-type for pacific

- app/actors/hyrax/actors/thesis_or_dissertation_work_actor.rb
- app/controllers/hyrax/thesis_or_dissertation_works_controller.rb
- app/forms/hyrax/thesis_or_dissertation_work_form.rb
- app/indexers/thesis_or_dissertation_work_indexer.rb
- app/models/thesis_or_dissertation_work.rb
- app/presenters/hyrax/thesis_or_dissertation_work_presenter.rb
- app/views/hyrax/thesis_or_dissertation_works/_thesis_or_dissertation_work.html.erb
- config/authorities/resource_types.yml
- config/initializers/hyrax.rb
- config/locales/thesis_or_dissertation_work.de.yml
- config/locales/thesis_or_dissertation_work.en.yml
- config/locales/thesis_or_dissertation_work.es.yml
- config/locales/thesis_or_dissertation_work.fr.yml
- config/locales/thesis_or_dissertation_work.it.yml
- config/locales/thesis_or_dissertation_work.pt-BR.yml
- config/locales/thesis_or_dissertation_work.zh.yml
- spec/actors/hyrax/actors/thesis_or_dissertation_work_actor_spec.rb
- spec/controllers/hyrax/thesis_or_dissertation_works_controller_spec.rb
- spec/features/create_thesis_or_dissertation_work_spec.rb
- spec/forms/hyrax/thesis_or_dissertation_work_form_spec.rb
- spec/models/thesis_or_dissertation_work_spec.rb
- spec/presenters/hyrax/thesis_or_dissertation_work_presenter_spec.rb
This Pr adds TesisOrDissertationWork work-type for pacific
> Completed ThesisOrDissertationWork for pacific

- app/actors/hyrax/actors/book_work_actor.rb
- app/controllers/hyrax/book_works_controller.rb
- app/forms/hyrax/book_work_form.rb
- app/indexers/book_work_indexer.rb
- app/models/book_work.rb
- app/presenters/hyrax/book_work_presenter.rb
- app/views/hyrax/book_works/_book_work.html.erb
- config/authorities/resource_types.yml
- config/initializers/hyrax.rb
- config/locales/book_work.de.yml
- config/locales/book_work.en.yml
- config/locales/book_work.es.yml
- config/locales/book_work.fr.yml
- config/locales/book_work.it.yml
- config/locales/book_work.pt-BR.yml
- config/locales/book_work.zh.yml
- spec/actors/hyrax/actors/book_work_actor_spec.rb
- spec/controllers/hyrax/book_works_controller_spec.rb
- spec/features/create_book_work_spec.rb
- spec/forms/hyrax/book_work_form_spec.rb
- spec/models/book_work_spec.rb
- spec/presenters/hyrax/book_work_presenter_spec.rb
This PR adds a bookwork work-type for Pacific
> Complete BookWork worktype for pacific

- app/actors/hyrax/actors/article_work_actor.rb
- app/controllers/hyrax/article_works_controller.rb
- app/forms/hyrax/article_work_form.rb
- app/indexers/article_work_indexer.rb
- app/models/article_work.rb
- app/presenters/hyrax/article_work_presenter.rb
- app/views/hyrax/article_works/_article_work.html.erb
- config/authorities/resource_types.yml
- config/initializers/hyrax.rb
- config/locales/article_work.de.yml
- config/locales/article_work.en.yml
- config/locales/article_work.es.yml
- config/locales/article_work.fr.yml
- config/locales/article_work.it.yml
- config/locales/article_work.pt-BR.yml
- config/locales/article_work.zh.yml
- spec/actors/hyrax/actors/article_work_actor_spec.rb
- spec/controllers/hyrax/article_works_controller_spec.rb
- spec/features/create_article_work_spec.rb
- spec/forms/hyrax/article_work_form_spec.rb
- spec/models/article_work_spec.rb
- spec/presenters/hyrax/article_work_presenter_spec.rb
> Complete ArticleWork for pacific

- app/controllers/catalog_controller.rb
- app/forms/hyrax/news_clipping_form.rb
- app/models/concerns/ubiquity/shared_metadata.rb
- app/models/solr_document.rb
- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- config/authorities/resource_types.yml
- config/locales/article_work.en.yml
- config/locales/book_chapter.en.yml
- config/locales/book_work.en.yml
- config/locales/image.en.yml
- config/locales/media.en.yml
- config/locales/presentation.en.yml
- config/locales/text_work.en.yml
- config/locales/thesis_or_dissertation_work.en.yml
- config/locales/uncategorized.en.yml
This PR adds the description to each work types and updates the resource type list
> Add description for each work type and updated resource types

- app/views/api/v1/work/_work.json.jbuilder
This PR adds the additional fields wanted by pacific to the API
> Additional fields for pacific added to the api

- app/controllers/api/v1/highlights_controller.rb
- app/controllers/api/v1/tenant_controller.rb
- app/controllers/api/v1/work_controller.rb
https://ubiquitypress.atlassian.net/browse/REPO-557
> ensure single work endpoint queries by id alone

- app/controllers/catalog_controller.rb
- app/forms/hyrax/news_clipping_form.rb
- app/models/concerns/ubiquity/shared_metadata.rb
- app/models/solr_document.rb
- app/presenters/hyku/manifest_enabled_work_show_presenter.rb
- app/views/api/v1/work/_work.json.jbuilder
- app/views/hyrax/base/_attribute_rows.html.erb
- config/locales/article_work.en.yml
- config/locales/book_work.en.yml
- config/locales/image_work.en.yml
- config/locales/thesis_or_dissertation_work.en.yml
This PR adds the following fields for NewsClipping form
photo_description
photo_caption
> Pacific additional fields

- config/authorities/licenses.yml
> add additional licences to be available through the importer

- app/forms/hyrax/book_chapter_form.rb
- app/forms/hyrax/book_work_form.rb
- app/models/concerns/ubiquity/shared_metadata.rb
- app/views/api/v1/work/_work.json.jbuilder
this Pr adds the new field buy_book:
https://ubiquitypress.atlassian.net/secure/RapidBoard.jspa?rapidView=6&projectKey=REPO&modal=detail&selectedIssue=REPO-560
> add new field buy book

- app/views/shared/ubiquity/contributor/_contributor_form_fields.html.erb
- app/views/shared/ubiquity/creator/_creator_form_fields.html.erb
- app/views/shared/ubiquity/json_fields_partials/_institutional_dropdown.erb
- app/views/shared/ubiquity/json_fields_partials/_institutional_relationship.html.erb
- app/views/shared/ubiquity/json_fields_partials/_institutional_text_field.erb
- docker/docker-compose.no-load-balance-dev.yml
This PR address the case when the institutional relationship field needs to be a text field
> Institutional relationship

- app/services/ubiquity/json_import/add_files.rb
- app/services/ubiquity/queue_import.rb
https://ubiquitypress.atlassian.net/browse/REPO-564
> "re-importing a work with same files will not create duplicate files

- app/jobs/attach_files_to_work_via_json_importer_job.rb
- app/services/ubiquity/queue_import.rb
> json-importer can set files as embargo and lease

- app/services/ubiquity/json_importer.rb
> add works to collection by saving the collection into the work using member_of_collections

- app/helpers/ubiquity/settings_helper.rb
- app/views/shared/ubiquity/contributor/_contributor_form_fields.html.erb
- app/views/shared/ubiquity/creator/_creator_form_fields.html.erb
- app/views/shared/ubiquity/json_fields_partials/_role.html.erb
- config/authorities/contributor_group.yml
> make role key in creator and contributor json to be configurable from settings

- app/controllers/api/v1/highlights_controller.rb
- app/controllers/concerns/ubiquity/api_controller_utility_methods.rb
> Api highlights endpoint should return content based on user role or cancan authorization ability

- app/controllers/api/v1/api_base_controller.rb
- app/controllers/api/v1/sessions_controller.rb
- app/controllers/concerns/ubiquity/api_controller_utility_methods.rb
- config/application.rb
> Api should send jwt as httponly cookie

- app/views/_logo.html.erb
- app/views/_masthead.html.erb
Requires a new environment variable:
SHOW_LOG_OUT: 'true'
> unhide logout and login button

- .gitignore
- app/controllers/hyku/registrations_controller.rb
- app/models/concerns/ubiquity/email_format.rb
- config/application.rb
- config/settings.yml
- spec/factories/users.rb
- spec/models/user_spec.rb
> Allows users to sign up and adds validation for an email format.

- app/models/article.rb
- app/models/article_work.rb
- app/models/book.rb
- app/models/book_chapter.rb
- app/models/book_contribution.rb
- app/models/book_work.rb
- app/models/concerns/ubiquity/work_type_validator.rb
- app/models/conference_item.rb
- app/models/dataset.rb
- app/models/exhibition_item.rb
- app/models/generic_work.rb
- app/models/image.rb
- app/models/image_work.rb
- app/models/media.rb
- app/models/news_clipping.rb
- app/models/presentation.rb
- app/models/report.rb
- app/models/text_work.rb
- app/models/thesis_or_dissertation.rb
- app/models/thesis_or_dissertation_work.rb
- app/models/time_based_media.rb
- app/models/uncategorized.rb
- app/services/ubiquity/queue_import.rb
https://ubiquitypress.atlassian.net/browse/REPO-565
> Custom validation - validate that a work is in the list of work types specified in ENV before  creating that work in the db

- app/views/records/edit_fields/_doi.html.erb
> Fixes undefined method for doi field

- app/views/records/edit_fields/_org_unit.html.erb
Removes undefined metadata_field method to fix error
> Fixes org unit form by removing metadata_field.

- app/controllers/api/v1/api_base_controller.rb
- app/controllers/api/v1/registrations_controller.rb
- app/controllers/api/v1/sessions_controller.rb
- app/controllers/concerns/ubiquity/api_user_utils.rb
- config/routes.rb
Ed's changes for user Sign Up. Tests to follow
> api user registration

- spec/requests/api/v1/user_signup_spec.rb
> Api user signup tests

- app/views/devise/shared/_links.html.erb
Not the most elegant solution but it will work for now I think
> Comments out link from _links page

- .gitignore
- app/assets/javascripts/ubiquity/creator.js
Fixes BL edit field issue showing personal fields on org creator edits
> Bl edit field

- app/controllers/api/v1/search_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/concerns/ubiquity/collections_controller_behaviour_override.rb
- app/controllers/concerns/ubiquity/collections_controller_override.rb
- app/models/collection.rb
- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/models/concerns/ubiquity/collection_behaviour_override.rb
- app/views/shared/ubiquity/collections/_list_collections.html.erb
- config/application.rb
Requires the addition of the line below to the environment variable
"turn_off_fedora_collection_work_association":  "true"
> Adding works to a colection via the ui should populate collection_id and collection_names metadata property

- app/services/ubiquity/parse_tenant_work_settings.rb
> Adds ParseTenantWorkSettings class

- app/helpers/application_helper.rb
- app/services/ubiquity/fetch_tenant_url.rb
requires change to local env settings: 
For example BL: 
"sub_cname": { "api": "bl.oar.bl.uk",
"live": "bl.iro.bl.uk"}
> Oai pmh url fix

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/sessions_controller.rb
- app/controllers/concerns/ubiquity/api_user_utils.rb
> Rest api samesite cookie fix

- app/controllers/concerns/ubiquity/collections_controller_behaviour_override.rb
- app/controllers/concerns/ubiquity/collections_controller_override.rb
- app/jobs/ubiquity_remove_child_records_job.rb
- app/models/concerns/ubiquity/collection_behaviour_override.rb
- app/services/ubiquity/indexer_client.rb
- app/services/ubiquity/remove_child_records.rb
> refactor code for adding collection id to work

- app/controllers/api/v1/search_controller.rb
- app/controllers/catalog_controller.rb
- app/controllers/concerns/ubiquity/collections_controller_behaviour_override.rb
- app/controllers/concerns/ubiquity/collections_controller_override.rb
- app/jobs/ubiquity_remove_child_records_job.rb
- app/models/collection.rb
- app/models/concerns/ubiquity/basic_metadata_decorator.rb
- app/models/concerns/ubiquity/collection_behaviour_override.rb
- app/services/ubiquity/indexer_client.rb
- app/services/ubiquity/remove_child_records.rb
- config/application.rb
> allow bl to add collection_id to works

- app/services/ubiquity/fetch_tenant_url.rb
Uses hash structure: `"sub_cname": { "bl": {"api": "bl.oar.bl.uk", "live": "bl.iro.bl.uk"},
"bl-demo": {"api": "bl-demo.oar.bl.uk", "live": "bl-demo.iro.bl.uk"}
}` etc
Also guards against crashes when no settings are present
> Oai pmh refactor

- app/services/ubiquity/fetch_tenant_url.rb
Adds settings guard to pacific codebase
> Brings guard code over to Pacific

- app/services/ubiquity/fetch_tenant_url.rb
Changes code to use per_account_settings
> Settings name change for pacific

- app/controllers/concerns/ubiquity/collections_controller_behaviour_override.rb
- app/controllers/concerns/ubiquity/collections_controller_override.rb
> add feature flag to switch off fedora collection and work association per account

- lib/tasks/ubiquity_resave_records.rake
> add rake task to resave works adding collection_id and collection_names avoiding fedora association between works and collections

- app/controllers/concerns/ubiquity/collections_controller_behaviour_override.rb
- app/services/ubiquity/fetch_tenant_url.rb
- app/services/ubiquity/json_importer.rb
> update bl json importer

- app/controllers/api/v1/registrations_controller.rb
- app/controllers/api/v1/sessions_controller.rb
- app/models/concerns/ubiquity/email_format.rb
- app/models/user.rb
- db/migrate/20200402132600_add_confirmable_attributes_to_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/requests/api/v1/sessions_spec.rb
- spec/requests/api/v1/user_signup_spec.rb
This pull request removes email format validation for the purposes of testing. Will need to be turned on before the code is deployed to live
> Pacific user registration

- app/models/concerns/ubiquity/update_shared_index.rb
- app/services/ubiquity/api_utils.rb
> Bl update collection names works

- app/controllers/api/v1/search_controller.rb
- app/controllers/concerns/ubiquity/collections_controller_behaviour_override.rb
- app/controllers/concerns/ubiquity/collections_controller_override.rb
- app/jobs/ubiquity_collection_child_records_job.rb
- app/models/concerns/ubiquity/collection_behaviour_override.rb
- app/services/ubiquity/manage_collection_child_records.rb
> move adding work to collection to background job and return collection_names_sim in api search facets

- app/views/devise/shared/_links.html.erb
Really simple change but took a while to figure out what was going on
> change to _links conditional to remove unexpected behaviors

- config/application.rb
Fixes #issuenumber ; refs #issuenumber
Present tense short summary (50 characters or less)
More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.
Description can have multiple paragraphs and you can use code examples inside:
``` ruby
class PostsController
def index
respond_with Post.limit(10)
end
end
```
Changes proposed in this pull request:
*
*
*
@samvera/hyrax-code-reviewers
> Removes eronious colons

- app/controllers/api/v1/search_controller.rb
- app/services/ubiquity/api_utils.rb
> fetching work via api should return the collection it belongs to. Also querying by multiple words should work

- app/actors/hyrax/actors/ubiquity_shared_actor.rb
- app/controllers/concerns/ubiquity/works_controller_behaviour_override.rb
- app/forms/concerns/ubiquity/hyrax_work_form_override.rb
- app/forms/ubiquity/all_forms_shared_behaviour.rb
- app/helpers/application_helper.rb
- app/views/shared/ubiquity/works/_fedora_form_member_of_collections.html.erb
- app/views/shared/ubiquity/works/_form_member_of_collections.html.erb
- app/views/shared/ubiquity/works/_non_fedora_form_member_of_collections.html.erb
- config/application.rb
> enabled works to be added to collection via relationship tab

- app/controllers/api/v1/highlights_controller.rb
> ensure api  highlights endpoint does not error out

- app/actors/hyrax/actors/ubiquity_shared_actor.rb
- app/controllers/concerns/ubiquity/works_controller_behaviour_override.rb
- app/forms/concerns/ubiquity/hyrax_work_form_override.rb
- app/forms/ubiquity/all_forms_shared_behaviour.rb
- app/helpers/ubiquity/settings_helper.rb
- app/views/shared/ubiquity/works/_fedora_form_member_of_collections.html.erb
- app/views/shared/ubiquity/works/_form_member_of_collections.html.erb
- app/views/shared/ubiquity/works/_non_fedora_form_member_of_collections.html.erb
- config/application.rb
> add work to collection via relationship tab

- app/controllers/api/v1/highlights_controller.rb
> check and avoid nil error in api highlights endpoint

- app/controllers/api/v1/search_controller.rb
> refactor api search for bl

- app/controllers/api/v1/search_controller.rb
> Pacific api search refactor

- app/controllers/application_controller.rb
> redirect to live url if the live key in settings have a value

- app/views/_logo.html.erb
> redirect homepage link to the live react sites

- app/views/_logo.html.erb
> remove check so redirection can work on live

- app/controllers/application_controller.rb
> remove logout redirect check so it works on live

- app/services/ubiquity/exporter/csv_data_remap.rb
> added pacific fields to list of field names for export

- app/views/records/edit_fields/_isbn.html.erb
- config/authorities/resource_types.yml
> fix error in isbn template and resource_type.yml

- app/services/ubiquity/json_importer.rb
Gives the ability to import a work to multiple collections via the importer
> Import work to multiple collections

- app/controllers/api/v1/sessions_controller.rb
- app/controllers/application_controller.rb
> Reusing jwt token to login redirect from react frontend to Hyku

- app/controllers/application_controller.rb
> Changed to use TENANT_SETTINGS

- app/controllers/api/v1/search_controller.rb
- app/controllers/concerns/ubiquity/collections_controller_behaviour_override.rb
- app/models/concerns/ubiquity/caching_single.rb
- app/views/api/v1/work/_work.json.jbuilder
> Ensure api facet return counts wthout a query term and adding work to a collection burst some cache keys

- app/models/concerns/ubiquity/caching_single.rb
> add ability to clear cache for the highlights page

- app/controllers/api/v1/search_controller.rb
> fix facet caching

- app/models/concerns/ubiquity/caching_single.rb
> put guard against when no redis_cache settings

- lib/tasks/ubiquity_resave_records.rake
> make rake task for resaving all works to accept date range for querying

- app/controllers/api/v1/collection_controller.rb
- app/controllers/api/v1/highlights_controller.rb
- app/controllers/api/v1/work_controller.rb
- app/controllers/concerns/ubiquity/api_controller_utility_methods.rb
> remove wotks with restricted visibility from public api

- app/controllers/concerns/ubiquity/collections_controller_behaviour_override.rb
- app/helpers/application_helper.rb
> remove duplicate works when displaying a collection

- app/controllers/concerns/ubiquity/collections_controller_behaviour_override.rb
- app/services/ubiquity/json_importer.rb
Fixes for 2 Sentry errors: 
https://sentry.ubiquity.press/ubiquitypress/repository/issues/611/?query=is%3Aunresolved
https://sentry.ubiquity.press/ubiquitypress/repository/issues/639/?query=is%3Aunresolved
This is an attempt at fixing these errors but have not tested that they work as they should.
> Atempts to fix some sentry errors that cropped up in BL use.

- app/controllers/hyku/registrations_controller.rb
- app/helpers/application_helper.rb
- app/views/devise/shared/_links.html.erb
Refactors setting that was missing from overall refactor and refactors the sign up link to use 'allow_signup' setting
> Changes sign up link to use allow sign up setting

- app/models/concerns/ubiquity/email_format.rb
- app/presenters/concerns/ubiquity/select_type_list_presenter_override.rb
Adds guard against nil account
> Guards against no tenant

- app/controllers/admin/exports_controller.rb
- app/jobs/ubiquity_export_csv_delete.rb
- app/jobs/ubiquity_exporter_job.rb
- app/models/concerns/ubiquity/csv_export_util.rb
- app/services/ubiquity/csv_data.rb
- app/services/ubiquity/csv_data_remap.rb
- app/services/ubiquity/csv_export_orchestrator.rb
- app/services/ubiquity/csv_generator.rb
- app/services/ubiquity/redis_storage.rb
- app/services/ubiquity/s3_wrapper.rb
- app/views/admin/exports/index.html.erb
- config/initializers/redis.rb
- config/routes.rb
- config/schedule.yml
> refactor csv download to happen in a background job and store files in S3

- app/views/hyrax/batch_edits/edit.html.erb
- app/views/shared/ubiquity/batch_edits/_edit.html.erb
> hide description tab in bulk edit page

- app/models/concerns/ubiquity/email_format.rb
Small change to look for default email if none in per account hash
> Changes email format to be conditional

- app/controllers/concerns/ubiquity/hyrax_my_controller_override.rb
- app/views/hyrax/dashboard/_sidebar.html.erb
- app/views/shared/ubiquity/batch_edits/_edit.html.erb
- config/application.rb
> Changes to enable new workflow to hide private collections from facet using bulk edit of the visibility of works in the private collection

- app/controllers/admin/exports_controller.rb
- app/services/ubiquity/csv_export_orchestrator.rb
> Change the text shown during CSV export process for the flash message and for notication messages

- app/views/admin/exports/index.html.erb
> Further CSV export text changes

- app/assets/javascripts/ubiquity/work_page.js
- app/services/ubiquity/csv_export_orchestrator.rb
- app/views/shared/ubiquity/batch_edits/_edit.html.erb
> text changes and allowing csv export link to open in a new tab

- app/services/ubiquity/s3_wrapper.rb
> Guard agains nil error

- app/controllers/admin/exports_controller.rb
- app/services/ubiquity/csv_export_orchestrator.rb
- app/services/ubiquity/s3_wrapper.rb
> fix csv exporter not filtering record by tenant

- app/controllers/admin/exports_controller.rb
- app/jobs/ubiquity_exporter_job.rb
- app/models/concerns/ubiquity/csv_export_util.rb
- app/services/ubiquity/exporter/csv_data.rb
- app/services/ubiquity/exporter/csv_data_remap.rb
- app/services/ubiquity/exporter/csv_export_orchestrator.rb
- app/services/ubiquity/exporter/csv_generator.rb
- app/services/ubiquity/redis_storage.rb
- app/services/ubiquity/s3_wrapper.rb
- app/views/admin/exports/index.html.erb
- config/routes.rb
> Update to Pacific CSV expoerter to use background jobs

- app/jobs/ubiquity_collection_child_records_job.rb
- app/models/concerns/ubiquity/collection_behaviour_override.rb
- app/services/ubiquity/manage_collection_child_records.rb
> Stop errors during deletion of collection containing works

- app/jobs/ubiquity_exporter_job.rb
- app/models/concerns/ubiquity/csv_export_util.rb
- app/services/ubiquity/exporter/csv_data.rb
- app/services/ubiquity/exporter/csv_export_orchestrator.rb
- app/services/ubiquity/exporter/csv_generator.rb
- app/services/ubiquity/s3_wrapper.rb
- app/views/admin/exports/index.html.erb
> Export CSV in batches of 1500 records in each file and zipped to S3

- app/models/concerns/ubiquity/csv_export_util.rb
- app/services/ubiquity/exporter/csv_data.rb
- app/services/ubiquity/exporter/csv_generator.rb
> Still export in batches but does not generate CSV after each batch but in one go after the the whole batch has ran

- app/models/concerns/ubiquity/csv_export_util.rb
- app/services/ubiquity/exporter/csv_data.rb
- app/services/ubiquity/exporter/csv_data_remap.rb
> Track remapped metadata fields in an array for use in reordering CSV header keys

- app/controllers/concerns/ubiquity/collections_controller_behaviour_override.rb
- app/helpers/ubiquity/settings_helper.rb
> Ensure collection presenter gets the right object after query, so empty collection still loads

- app/models/concerns/ubiquity/collection_behaviour_override.rb
> Move deleting the works in a collection to a background job

- app/assets/javascripts/ubiquity/work_page.js
- app/controllers/concerns/ubiquity/hyrax_my_controller_override.rb
- app/views/hyrax/batch_edits/edit.html.erb
- app/views/hyrax/dashboard/_sidebar.html.erb
- app/views/shared/ubiquity/batch_edits/_edit.html.erb
- config/application.rb
> Update collections with code from BL branch. Hide collections for non admin, in dahboard/ works list the collections in dropdown filter

- app/services/ubiquity/csv_data_remap.rb
> Fix Bl to correctly export alternate_identifier and also export admin_set title and id

- app/services/ubiquity/json_importer.rb
> Minor change to import admin_set by id

- app/assets/javascripts/ubiquity/datacite.js
- app/services/ubiquity/crossref_response.rb
- app/services/ubiquity/datacite_client.rb
- app/services/ubiquity/datacite_response.rb
> Auto populate forms using the new Api's for datacite and crossref

- app/services/ubiquity/csv_data_remap.rb
> Fix to ensure exporter exports collection id for works in a collection

- app/services/ubiquity/json_importer.rb
> Ensure Importer can update a work with loosing its connection to a collection

- app/views/_logo.html.erb
> Implements redirect for BL

- app/services/ubiquity/exporter/csv_data_remap.rb
> ensure pacific exporter includes collection id

- app/assets/javascripts/ubiquity/work_page.js
- app/controllers/concerns/ubiquity/hyrax_my_controller_override.rb
> Ensure facet filter on dashboard/work returns all collections when more is clicked

- app/assets/javascripts/ubiquity/work_page.js
- app/controllers/concerns/ubiquity/hyrax_my_controller_override.rb
> Updated collection filter with a label

- app/assets/javascripts/ubiquity/datacite.js
- app/services/ubiquity/datacite_client.rb
- app/services/ubiquity/datacite_response.rb
- app/views/shared/ubiquity/contributor/_new_form.html.erb
> Ensure contributor fields are auto-populated after api calls

- app/services/ubiquity/json_importer.rb
> Fix for adding and removing collection via the importer

- app/services/ubiquity/api/redirect_work_id_in_workflow_notification.rb
- app/services/ubiquity/parse_tenant_work_settings.rb
- app/views/shared/ubiquity/notifications/_notifications.html.erb
> Fix for notification error

- app/models/concerns/ubiquity/caching_single.rb
- app/services/ubiquity/api_utils.rb
- app/views/hyrax/base/_attribute_rows.html.erb
> Remove fedora association query when fetching the works in a collection

- app/assets/javascripts/ubiquity/datacite.js
- app/services/ubiquity/crossref_response.rb
- app/services/ubiquity/datacite_response.rb
> refactor to auto-populate funders field from datacite and crossref api

- app/models/concerns/ubiquity/all_models_virtual_fields.rb
- lib/tasks/ubiquity_update_current_he_instiution_to_json.rake
> Rake task to resave the current_he_institution field as JSON

- app/assets/javascripts/application.js
- app/assets/javascripts/ubiquity/datacite.js
- app/assets/javascripts/ubiquity/funder.js
- app/assets/javascripts/ubiquity/funder_awards.js
- app/forms/ubiquity/all_forms_shared_behaviour.rb
- app/views/shared/ubiquity/funder/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/funder/_new_form.html.erb
- app/views/shared/ubiquity/funder/_show_array_hash.html.erb
Added ISNI and ROR fields in funder
> Added ISNI and ROR field in funder

- app/views/hyrax/base/_attribute_rows.html.erb
- app/views/shared/ubiquity/funder/_edit_array_hash_form.html.erb
- app/views/shared/ubiquity/funder/_new_form.html.erb
Changed the autocomplete url for funders name in deposit form
> Added cross ref url for searching funder names

- app/views/api/v1/work/_work_content.jbuilder
> Move thumbnail code to Pacific

- config/tinymce.yml
> adds `relative_urls : false` to tinymce.yaml

- app/assets/javascripts/ubiquity/datacite.js
- app/views/shared/ubiquity/contributor/_show_array_hash.html.erb
> Bl freya fields reorder populate funder awards

- app/views/shared/ubiquity/funder/_edit_array_hash_form.html.erb
> Ensure thesis worktype does not throw nil error from funder field when edit is clicked

- app/assets/javascripts/application.js
- app/assets/javascripts/ubiquity/funder.js
- app/assets/javascripts/ubiquity/funder_awards.js
- app/assets/javascripts/ubiquity/funder_validation.js
Fixes REPO-791 following the pattern of ORCID/ISNI validation.
> Funder name must be present if an award is present

- app/models/concerns/ubiquity/all_models_virtual_fields.rb
Fix for the blank entry of awards if the funder name is not present for the particular record
> Added check for the funder name in the funder group

- app/views/api/v1/work/_work.json.jbuilder
> Shared layer patch

- app/services/ubiquity/csv_data_remap.rb
> fix for error when exporting generic work

- app/assets/javascripts/ubiquity/funder.js
- app/assets/javascripts/ubiquity/funder_autocomplete_callback.js
> remove funder award from a funder after api call to crossref

- app/views/shared/ubiquity/related_identifier/_show_array_hash.html.erb
> Bl ensure swp can load with incomplete related identifier

- app/services/concerns/ubiquity/crossref_generic_authority_override.rb
- app/services/ubiquity/datacite_client.rb
- config/application.rb
> append mailto to  FOR all crossref api  query

- app/services/ubiquity/csv_data_remap.rb
Adds missing columns and removes _1's on columns that are used as single value for user experience
> Makes tweaks to exporter based on google doc

- app/models/concerns/ubiquity/all_models_virtual_fields.rb
Fixes https://sentry.ubiquity.press/ubiquitypress/repository/issues/1347/
Part of REPO-801
> Guard against empty string for funder

- app/services/ubiquity/csv_data_remap.rb
> Removes _1 from journal_title
